import { potion, ef } from './helpers.js';

export const PACK_CONSUMABLES = [
  /* healing — event/exchange only, never shop dilution */
  potion({ id: 'cp_stitchleaf_tonic', name: 'Stitchleaf Tonic', heal: 28, desc: 'Moderate healing; stronger below 35% HP.',
    effects: [ef('onConsumable', 'heal', { pct: 0.06, when: { hpBelow: 0.35 } })] }),
  potion({ id: 'cp_slowheart_draught', name: 'Slowheart Draught', heal: 12, desc: 'Heals over several turns instead of immediately.',
    effects: [ef('onConsumable', 'setFlag', { key: 'hot', scope: 'combat', value: 8 })] }),
  potion({ id: 'cp_gate_salt_vial', name: 'Gate-Salt Vial', heal: 14, desc: 'Small heal plus removal of one gate- or curse-related mark.',
    effects: [ef('onConsumable', 'removeStatus', { status: 'hexed' })] }),
  potion({ id: 'cp_ashmilk_flask', name: 'Ashmilk Flask', heal: 18, desc: 'Heals and temporarily resists burn; lowers precision briefly.',
    effects: [ef('onConsumable', 'removeStatus', { status: 'burn' })] }),
  potion({ id: 'cp_iceblood_cordial', name: 'Iceblood Cordial', heal: 10, desc: 'Prevents the next freeze or stun and heals slightly.',
    effects: [ef('onConsumable', 'removeStatus', { status: 'frozen' }),
      ef('onConsumable', 'armNextIncoming', { mult: 0.88 })] }),
  potion({ id: 'cp_bog_antivenom', name: 'Bog Antivenom', heal: 8, desc: 'Removes poison and converts part of the removed duration into healing.',
    effects: [ef('onConsumable', 'removeStatus', { status: 'poison' }), ef('onConsumable', 'heal', { amount: 10 })] }),
  potion({ id: 'cp_mercy_draught', name: 'Mercy Draught', healPct: 0.22, desc: 'Stronger when used on another player.',
    effects: [ef('onConsumable', 'shareHeal', { pct: 0.25 })] }),
  potion({ id: 'cp_last_companions_dose', name: "Last Companion's Dose", healPct: 0.4, desc: 'Very strong heal, usable only on the lowest-health party member.',
    effects: [ef('onConsumable', 'heal', { pct: 0.1, when: { hpBelow: 0.5 } })] }),
  potion({ id: 'cp_crimson_continuance', name: 'Crimson Continuance', desc: 'Prevents defeat at 1 HP but applies a max-HP wound until campfire.',
    effects: [ef('onConsumable', 'lethalWard', { mutex: 'lethal_ward', maxHp: -2 })] }),
  potion({ id: 'cp_pilgrims_shared_cup', name: "Pilgrim's Shared Cup", healPct: 0.12, desc: 'Divides healing among all living party members.',
    effects: [ef('onConsumable', 'shareHeal', { pct: 1 })] }),
  potion({ id: 'cp_corpse_flower_nectar', name: 'Corpse-Flower Nectar', heal: 20, desc: 'Healing type depends on the most recently defeated enemy.',
    effects: [ef('onConsumable', 'heal', { amount: 16 })] }),
  potion({ id: 'cp_unregistered_remedy', name: 'Unregistered Remedy', heal: 36, desc: 'Strong healing that does not count as a normal potion for certain event trades.',
    effects: [ef('onConsumable', 'heal', { amount: 8 }),
      ef('onConsumable', 'setFlag', { key: 'unregisteredHeal', scope: 'run', persistFlag: true })] }),

  potion({ id: 'cp_kilnfire_ampoule', name: 'Kilnfire Ampoule', bombDmg: 18, desc: 'Applies burn; stronger against shielded targets.',
    effects: [ef('onConsumable', 'applyStatus', { status: 'burn', turns: 2 })] }),
  potion({ id: 'cp_rootbomb', name: 'Rootbomb', bombDmg: 12, desc: 'Roots or slows enemies; Forest enemies may resist.',
    effects: [ef('onConsumable', 'applyStatus', { status: 'lazy', turns: 1 })] }),
  potion({ id: 'cp_frostglass_dust', name: 'Frostglass Dust', desc: 'Makes the next heavy hit apply brittle (frail).',
    effects: [ef('onConsumable', 'applyStatus', { status: 'frail', turns: 2 })] }),
  potion({ id: 'cp_bogfire_jar', name: 'Bogfire Jar', bombDmg: 10, desc: 'Applies poison and burn with lower individual strength.',
    effects: [ef('onConsumable', 'applyStatus', { status: 'poison', turns: 2 })] }),
  potion({ id: 'cp_gate_nail_bundle', name: 'Gate-Nail Bundle', desc: 'Reduces or delays an enemy\'s next charge gain.',
    effects: [ef('onConsumable', 'reduceCharge', { amount: 2 })] }),
  potion({ id: 'cp_mirror_coin', name: 'Mirror Coin', desc: 'Reflects one minor targeted status (bounded).',
    effects: [ef('onConsumable', 'convertStatus', { status: 'weaken', statusTo: 'marked' })] }),
  potion({ id: 'cp_funeral_salt', name: 'Funeral Salt', bombDmg: 16, desc: 'Damages undead and weakens summons.',
    effects: [ef('onConsumable', 'applyStatus', { status: 'frail', turns: 2 })] }),
  potion({ id: 'cp_bell_clapper_shard', name: 'Bell-Clapper Shard', desc: 'Interrupts a minor intent or reduces its effect.',
    effects: [ef('onConsumable', 'weakenIntent', { mult: 0.75 })] }),
  potion({ id: 'cp_crowned_deer_musk', name: 'Crowned-Deer Musk', desc: 'Redirects enemy attention (taunt flag).',
    effects: [ef('onConsumable', 'applyStatus', { status: 'marked', turns: 2 })] }),
  potion({ id: 'cp_invisible_toll_powder', name: 'Invisible Toll Powder', desc: 'The next enemy buff loses part of its potency.',
    effects: [ef('onConsumable', 'weakenIntent', { mult: 0.85 })] }),
  potion({ id: 'cp_dragon_soot_capsule', name: 'Dragon-Soot Capsule', desc: 'Adds an elemental rider based on bloodline or weapon.',
    effects: [ef('onConsumable', 'applyStatus', { status: 'burn', turns: 2 })] }),
  potion({ id: 'cp_echo_chalk', name: 'Echo Chalk', desc: 'Repeats the next basic action at reduced strength (depth 1).',
    effects: [ef('onConsumable', 'echoAction', { mult: 0.45, capability: 'echo_copy' })] }),
  potion({ id: 'cp_drowned_court_ink', name: 'Drowned Court Ink', desc: 'Marks a target so healing or shielding it causes damage.',
    effects: [ef('onConsumable', 'applyStatus', { status: 'marked', turns: 3 })] }),
  potion({ id: 'cp_system_static_grenade', name: 'System Static Grenade', desc: 'Scrambles one enemy non-signature action, with a previewed range.',
    effects: [ef('onConsumable', 'weakenIntent', { mult: 0.7 }), ef('onConsumable', 'revealIntent', { value: 'scrambled' })] }),
  potion({ id: 'cp_fame_eater_bait', name: 'Fame-Eater Bait', desc: 'Converts a small amount of Fame into a party-wide combat effect.',
    effects: [ef('onConsumable', 'spendFamePower', { fame: 2, mult: 1.1 })] }),

  potion({ id: 'cp_surveyors_flare', name: "Surveyor's Flare", desc: 'Reveals concealed enemies, traps, or phase changes.',
    effects: [ef('onConsumable', 'revealIntent', { value: 'shape' })] }),
  potion({ id: 'cp_gate_mason_wedge', name: "Gate Mason's Wedge", desc: 'Prevents one forced movement, target switch, or gate closure.',
    effects: [ef('onConsumable', 'armNextIncoming', { add: -6 })] }),
  potion({ id: 'cp_refugee_smokecloth', name: 'Refugee Smokecloth', desc: 'Reduces enemy attention on the user.',
    effects: [ef('onConsumable', 'armNextIncoming', { mult: 0.85 })] }),
  potion({ id: 'cp_frozen_hearth_coal', name: 'Frozen Hearth Coal', desc: 'Temporary party resistance to frost.',
    effects: [ef('onConsumable', 'removeStatus', { status: 'frozen' })] }),
  potion({ id: 'cp_swamp_reed_filter', name: 'Swamp Reed Filter', desc: 'Protects against the next poison event or combat application.',
    effects: [ef('onConsumable', 'removeStatus', { status: 'poison' }),
      ef('onConsumable', 'armNextIncoming', { mult: 0.9 })] }),
  potion({ id: 'cp_appeal_form_7b', name: 'Appeal Form 7-B', desc: 'Delays one System penalty until after combat.',
    effects: [ef('onConsumable', 'delayEffect', { delayTurns: 2, mult: 1 })] }),
  potion({ id: 'cp_portable_moss_shrine', name: 'Portable Moss Shrine', desc: 'Converts a small amount of gold into healing once.',
    effects: [ef('onConsumable', 'spendGoldPower', { gold: 20, mult: 1 }), ef('onConsumable', 'heal', { amount: 22 })] }),
  potion({ id: 'cp_hero_license_stamp', name: 'Hero-License Stamp', desc: 'Temporarily satisfies one Fame requirement.',
    effects: [ef('onConsumable', 'setFlag', { key: 'stamp', scope: 'floor' })] }),
  potion({ id: 'cp_black_ledger_eraser', name: 'Black-Ledger Eraser', desc: 'Removes one mark, debt, or bounty while creating a smaller hidden fee.',
    effects: [ef('onConsumable', 'clearFlag', { key: 'wanted', scope: 'run' })] }),
  potion({ id: 'cp_pack_oath_cord', name: 'Pack-Oath Cord', desc: 'Redirects part of one ally\'s incoming damage to the user.',
    effects: [ef('onConsumable', 'redirectDamage', { pct: 0.35, mutex: 'damage_redirect' })] }),
  potion({ id: 'cp_hingescale_varnish', name: 'Hingescale Varnish', desc: 'Temporarily adds elemental resistance to armor.',
    effects: [ef('onConsumable', 'armNextIncoming', { mult: 0.9 })] }),
  potion({ id: 'cp_possession_seal', name: 'Possession Seal', desc: 'Protects a selected item from one sacrifice, theft, or transformation.',
    effects: [ef('onConsumable', 'setFlag', { key: 'sealedItem', scope: 'run', persistFlag: true })] }),
  potion({ id: 'cp_returnee_red_thread', name: "Returnee's Red Thread", desc: 'Prevents the party from becoming separated during one event.',
    effects: [ef('onConsumable', 'armNextIncoming', { mult: 0.9, scope: 'floor' })] }),

  potion({ id: 'cp_blank_gate_permit', name: 'Blank Gate Permit', desc: 'Can be filled out during a bureaucracy event.',
    effects: [ef('onEventResolve', 'gainGold', { amount: 8, once: 'floor' }),
      ef('onEventResolve', 'setFlag', { key: 'permit', scope: 'run', persistFlag: true })] }),
  potion({ id: 'cp_reforging_resin', name: 'Reforging Resin', desc: 'Improves one kiln or smith outcome.',
    effects: [ef('onEventResolve', 'gainGold', { amount: 10, once: 'floor' })] }),
  potion({ id: 'cp_merchant_appraisal_lens', name: "Merchant's Appraisal Lens", desc: 'Reveals one hidden property before purchase.',
    effects: [ef('onShopAction', 'revealIntent', { value: 'property' })] }),
  potion({ id: 'cp_counterfeit_rank_badge', name: 'Counterfeit Rank Badge', desc: 'Bypasses one guild requirement but creates audit risk.',
    effects: [ef('onEventResolve', 'setFlag', { key: 'cp_audit_risk', scope: 'run', persistFlag: true })] }),
  potion({ id: 'cp_demon_queue_ticket', name: 'Demon Queue Ticket', desc: 'Converts one forced toll into a smaller future debt.',
    effects: [ef('onEventResolve', 'delayEffect', { delayTurns: 3 })] }),
  potion({ id: 'cp_funeral_receipt', name: 'Funeral Receipt', desc: 'Prevents Grave Tax from charging twice.',
    effects: [ef('onEventResolve', 'setFlag', { key: 'paidGrave', scope: 'run', persistFlag: true }),
      ef('onEventResolve', 'gainGold', { amount: 6, once: 'run' })] }),
  potion({ id: 'cp_royal_wax_seal', name: 'Royal Wax Seal', desc: 'Opens court choices or raises the sale value of one item.',
    effects: [ef('onEventResolve', 'setFlag', { key: 'royalSeal', scope: 'run', persistFlag: true })] }),
  potion({ id: 'cp_unminted_gate_coin', name: 'Unminted Gate Coin', desc: 'Accepted only by supernatural merchants.',
    effects: [ef('onEventResolve', 'convertResource', { key: 'unminted' })] }),
  potion({ id: 'cp_futures_contract_stub', name: 'Futures Contract Stub', desc: 'Reserve a reward category from a later event.',
    effects: [ef('onEventResolve', 'storeMemory', { key: 'futureCat', scope: 'run' })] }),
  potion({ id: 'cp_masons_chalk', name: "Mason's Chalk", desc: 'Reduces shortcut risk.',
    effects: [ef('onEventResolve', 'armNextIncoming', { mult: 0.9, scope: 'floor' })] }),
  potion({ id: 'cp_portable_kiln_brick', name: 'Portable Kiln Brick', desc: 'Allows one low-grade field reforge.',
    effects: [ef('onEventResolve', 'armNextHit', { add: 3, scope: 'floor' })] }),
  potion({ id: 'cp_memory_thread', name: 'Memory Thread', desc: 'Preserves one event choice from being erased or rewritten.',
    effects: [ef('onEventResolve', 'storeMemory', { key: 'preservedChoice', scope: 'run' })] }),
  potion({ id: 'cp_monster_lure_incense', name: 'Monster-Lure Incense', desc: 'Voluntarily converts a peaceful floor into a higher-reward encounter.',
    effects: [ef('onFloorStart', 'armNextHit', { add: 4, scope: 'floor' })] }),
  potion({ id: 'cp_pilgrims_ration', name: "Pilgrim's Ration", heal: 10, desc: 'Small healing now or better healing if saved until campfire.',
    effects: [ef('onCampfire', 'heal', { amount: 18 })] }),

  potion({ id: 'cp_potion_too_much_healing', name: 'Potion of Too Much Healing', healPct: 1, desc: 'Full heal followed by temporary reduced max HP.',
    effects: [ef('onConsumable', 'heal', { pct: 0.15 }),
      ef('onConsumable', 'armNextIncoming', { add: 5 })] }),
  potion({ id: 'cp_tomorrows_antidote', name: "Tomorrow's Antidote", desc: 'Removes the next negative status, but only after it triggers once.',
    effects: [ef('onConsumable', 'delayEffect', { delayTurns: 1 })] }),
  potion({ id: 'cp_false_resurrection_draught', name: 'False Resurrection Draught',
    desc: 'Creates an echo at defeat instead of reviving the original character.',
    playable: 'adapted', adaptation: 'Spawns a generated basic-action echo (depth 1) instead of a second climber or mid-combat restore.',
    effects: [ef('onConsumable', 'echoAction', { mult: 0.5, capability: 'echo_copy' })] }),
  potion({ id: 'cp_fame_distillate', name: 'Fame Distillate', desc: 'Gain combat power now and lose Fame afterward.',
    effects: [ef('onConsumable', 'spendFamePower', { fame: 4, mult: 1.2 })] }),
  potion({ id: 'cp_liquid_contract', name: 'Liquid Contract', desc: 'Choose the benefit immediately; the drawback is revealed but collected later.',
    effects: [ef('onConsumable', 'delayEffect', { delayTurns: 2, add: 6 })] }),
  potion({ id: 'cp_gate_parasite_culture', name: 'Gate-Parasite Culture', heal: 8, desc: 'Regenerates HP while applying an escalating parasite.',
    effects: [ef('onTurnStart', 'heal', { amount: 4 }), ef('onTurnStart', 'applyStatus', { status: 'poison', turns: 1 })] }),
  potion({ id: 'cp_drowned_memory_wine', name: 'Drowned Memory Wine', desc: 'Restore a used consumable but forget/revoke a minor event benefit.',
    effects: [ef('onConsumable', 'clearFlag', { key: 'minorBenefit', scope: 'run' })] }),
  potion({ id: 'cp_crimson_save_ink', name: 'Crimson Save Ink', desc: 'Records current HP and returns to that number later, whether higher or lower. Not a save-file restore.',
    effects: [ef('onConsumable', 'storeMemory', { key: 'savedHp', scope: 'combat', stat: 'hp' })] }),
  potion({ id: 'cp_heroic_overdose', name: 'Heroic Overdose', desc: 'Gain Battle Charge without altering turn-start generation; severe cooldown penalty afterward.',
    effects: [ef('onConsumable', 'grantCharge', { amount: 2 })] }),
  potion({ id: 'cp_system_crash_tonic', name: 'System-Crash Tonic', desc: 'Temporarily removes class restrictions from one technique but weakens it substantially.',
    effects: [ef('onConsumable', 'borrowTechnique', { skillId: 'basic_attack' })] }),
];
