import { ev, ch } from './helpers.js';
import { PACK_EVENTS } from './events_chains.js';
import './events_biomes.js';

const w = (label, hint, o, extra) => ch(label, hint, { text: hint, ...o }, extra);
const idc = (req, label, hint, o) => ch(label, hint, { text: hint, ...o }, { req, identity: true });
const clsEv = (id, classId, biome, title, text, choices, extra = {}) => ev({
  id, biome, title, text, glyph: extra.glyph || '✦', category: extra.cat || 'advancement',
  w: 5, once: true, tags: ['class-specific', 'secret-flag'],
  when: { classId }, affinity: { classes: [classId] },
  identityScope: extra.scope || 'actor',
  choices,
});

PACK_EVENTS.push(
  clsEv('cp_warrior_hold_world', 'warrior', 'ruins', 'Hold the World Shut',
    'A gate is collapsing outward. Someone has to be the hinge.', [
      w('Take severe HP damage to stabilize it', 'the party passes, Fame', { hp: -18, fame: 5, flag: 'cp_held_world' }),
      w('Let it collapse and find another way', 'HP for everyone later (flag)', { flag: 'cp_gate_collapsed', fame: -1 }),
    ], { glyph: '🛡️' }),
  clsEv('cp_warrior_sword_refuses_skill', 'warrior', 'frost', 'The Sword That Refuses Skill',
    'A sentient weapon challenges the Warrior to win the next combat using only basic attacks or Guard.', [
      w('Accept the trial', 'next combat: basics only (flag)', { flag: 'cp_basic_trial', item: 'cp_gatebreaker_greatsword' }),
      w('Refuse the blade', 'it sulks', { fame: 1 }),
    ], { glyph: '⚔️' }),
  clsEv('cp_ranger_three_trails', 'archer', 'forest', 'Three Trails, One Set of Footprints',
    'The Ranger may identify a treasure route, an NPC route, or the safest route. Choosing one permanently closes the others.', [
      w('Treasure route', 'gear, the other paths close', { item: 'cp_three_trails_longbow', flag: 'cp_trail_hunt' }),
      w('World-scent route', 'a legendary javelin, the other paths close', { item: 'cp_world_scent_javelin', flag: 'cp_trail_scent' }),
      w('NPC route', 'Fame and a name', { fame: 4, flag: 'cp_trail_rescue' }),
      w('Safest route', 'HP restored, quieter climb', { hpPct: 0.15, flag: 'cp_trail_escape' }),
    ], { glyph: '🏹' }),
  clsEv('cp_ranger_beast_no_name', 'archer', 'swamp', 'Beast Without a Name',
    'A wounded creature waits for a word.', [
      w('Name and spare it for future assistance', 'companion flag', { fame: 3, flag: 'cp_named_beast' }),
      w('Harvest it for gear material', 'slag', { item: 'cp_kiln_memory_slag' }),
      w('Track the hunter who wounded it', 'a trail', { flag: 'cp_hunter_trail', world: { knowledge: 'cp_wounded_hunter' } }),
    ], { glyph: '🐾' }),
  clsEv('cp_mage_illegal_margin', 'mage', 'ruins', 'Illegal Margin Note',
    'A spell written in the margin of reality can be learned by paying gold, max HP, or destroying another magical item. The cheapest price creates a corrupted version.', [
      w('Pay gold', 'clean copy', { gold: -55, item: 'cp_margin_script_staff' }, { req: { gold: 55 } }),
      w('Pay max HP', 'it writes in you', { maxHp: -4, item: 'cp_margin_script_staff' }),
      w('Destroy a magical item', 'offering', { offering: { kinds: ['pack'] }, item: 'cp_false_system_staff' }, { req: { offering: true } }),
      w('Take the cheapest corrupted version', 'it works, mostly', { gold: -15, item: 'cp_paradox_wand', flag: 'cp_corrupted_margin' }, { req: { gold: 15 } }),
    ], { glyph: '📜' }),
  clsEv('cp_mage_borrowed_element', 'mage', 'frost', 'Borrowed Element',
    'The Mage borrows power from the next biome, gaining an advantage now but strengthening an elemental enemy later.', [
      w('Borrow it', 'power now, flag later', { item: 'cp_frost_oracles_rod', flag: 'cp_borrowed_next_biome' }),
      w('Refuse the loan', 'you stay in this weather', { fame: 1 }),
    ], { glyph: '❄️' }),
  clsEv('cp_rogue_invisible_tollbooth', 'rogue', 'ruins', 'The Invisible Tollbooth',
    'The Rogue alone sees a hidden collector skimming every gate toll.', [
      w('Steal the reserve', 'gold', { gold: 55, flag: 'cp_toll_stolen' }),
      w('Expose the collector for Fame', 'whistle', { fame: 4, flag: 'cp_toll_exposed' }),
      w('Demand a percentage', 'ongoing skim (capped flag)', { gold: 25, flag: 'cp_toll_cut' }),
      w('Quietly remove the surcharge for everyone', 'kindness', { fame: 3, flag: 'cp_toll_removed' }),
    ], { glyph: '🪙' }),
  clsEv('cp_rogue_black_ledger', 'rogue', 'swamp', 'Black Ledger',
    'A book that will write whatever you tell it to.', [
      w('Erase a wanted flag', 'clean-ish', { flag: 'cp_wanted_cleared' }),
      w('Forge a heroic deed', 'Fame, audit risk', { fame: 4, flag: 'cp_audit_risk' }),
      w('Redirect a future fee', 'discount flag', { flag: 'cp_fee_redirect' }),
      w('Steal 60 gold and create an audit chain', 'loud money', { gold: 60, flag: 'cp_audit_risk' }),
    ], { glyph: '📒' }),
  clsEv('cp_priest_heretic_miracle', 'priest', 'forest', 'The Heretic Miracle',
    'A dying enemy performs a genuine miracle.', [
      w('Recognize it publicly', 'lose institutional Fame', { fame: -3, flag: 'cp_miracle_public', item: 'cp_heretics_bell' }),
      w('Suppress it', 'conventional blessing', { hpPct: 0.12, fame: 2, flag: 'cp_miracle_suppressed' }),
      w('Take the miracle into yourself', 'max-HP cost', { maxHp: -4, item: 'cp_nameless_reliquary' }),
      w('Preserve the evidence', 'later religious event', { flag: 'cp_miracle_evidence' }),
    ], { glyph: '✨' }),
  clsEv('cp_priest_reliquary_living', 'priest', 'hell', 'Reliquary of the Living',
    'The reliquary demands something still alive.', [
      w('Offer HP', 'blood', { hp: -12, item: 'cp_censer_funeral_gate' }),
      w('Offer max HP', 'deeper', { maxHp: -4, item: 'cp_staff_seven_forgotten_names' }),
      w('Refuse and release what is trapped inside', 'Fame', { fame: 4, flag: 'cp_reliquary_opened' }),
      w('Co-op: accept another player\'s voluntary burden', 'solo: you carry it', { hp: -8, fame: 2 }),
    ], { glyph: '⚱️' }),
  clsEv('cp_monk_empty_handed', 'monk', 'ruins', 'Empty-Handed Gate',
    'The gate opens only for someone carrying no worldly possessions.', [
      w('Temporarily entrust gear to the pack (floor-scoped)', 'you walk through light', { flag: 'cp_gear_entrusted', item: 'cp_empty_hand_seal' }),
      w('Surrender one item permanently', 'offering', { offering: { kinds: ['pack'] }, fame: 2 }, { req: { offering: true } }),
      w('Meditate and lose HP instead', 'the definition was always the body', { hp: -12, flag: 'cp_empty_meditated' }),
      w('Expose the gate\'s definition of possession as flawed', 'it opens anyway, and yields the staff of no possession', { fame: 3, flag: 'cp_possession_flawed', item: 'cp_staff_no_possession', resolveCurse: 'inventory_weak' }),
      w('Wear the robe that owns nothing', 'cursed emptiness', { item: 'cp_possessionless_robe', flag: 'cp_robe_worn' }),
    ], { glyph: '✋' }),
  clsEv('cp_monk_heartbeat_floor', 'monk', 'swamp', 'The Heartbeat Under the Floor',
    'Match the dungeon\'s rhythm, disrupt it, or silence it.', [
      w('Match it', 'defensive blessing', { flag: 'cp_rhythm_matched', item: 'cp_glacier_heart_beads' }),
      w('Disrupt it for gold hidden below', 'noise, coin', { gold: 45, flag: 'cp_rhythm_broken' }),
      w('Silence it', 'alter a future boss (flag)', { flag: 'cp_boss_silenced' }),
    ], { glyph: '💓' }),
  clsEv('cp_warlock_clause_inspection', 'warlock', 'ruins', 'Clause Inspection',
    'A contract is nailed to a door that should not have a door.', [
      w('Sign a cheaper clause', 'Pact now, debt later', { flag: 'cp_signed_cheap', item: 'cp_clause_seven_stylus' }),
      w('Pay HP to void it', 'blood as ink', { hp: -10, fame: 2, flag: 'cp_clause_voided' }),
      w('Redirect the invoice to a dungeon entity', 'not your name', { flag: 'cp_invoice_redirected' }),
    ], { glyph: '🖋️' }),
  clsEv('cp_warlock_unregistered_patron', 'warlock', 'hell', 'Unregistered Patron',
    'Something downstairs would like a word about your existing signature.', [
      w('Renegotiate', 'Fame for a better clause', { fame: -3, item: 'cp_appeal_denied_grimoire' }),
      w('Refuse the meeting', 'the invoice stays', { flag: 'cp_patron_refused' }),
      w('Offer the System as collateral', 'dangerous', { flag: 'cp_system_collateral', item: 'cp_seventh_signature_contract' }),
    ], { glyph: '📜' }),
  clsEv('cp_viking_keel_oath', 'viking', 'frost', 'Keel Oath',
    'A longship is frozen into the citadel wall, still trying to raid a kingdom that is not here.', [
      w('Swear on the keel', 'oath, HP', { hp: -10, fame: 3, item: 'cp_oath_to_the_keel', flag: 'cp_keel_sworn' }),
      w('Chop it free for timber and iron', 'gear', { item: 'cp_raid_prow_axe' }),
      w('Leave the raid unfinished', 'the ice keeps it', { fame: 1 }),
    ], { glyph: '🪓' }),
  clsEv('cp_viking_blood_price_hall', 'viking', 'hell', 'Blood-Price Hall',
    'A hall that only admits people who have already paid in HP.', [
      w('Pay and enter', 'Fury, a weapon', { hp: -12, item: 'cp_valhalla_boarding_axe', flag: 'cp_blood_hall' }),
      w('Refuse the bill', 'you keep your blood', { fame: 1 }),
      w('Offer someone else\'s debt (unanimous in co-op)', 'solo: you cannot', { fame: -2, flag: 'cp_blood_refused' }),
    ], { glyph: '🏟️' }),
  clsEv('cp_bard_wrong_encore', 'bard', 'frost', 'The Wrong Encore',
    'An audience demands a song you have not written yet.', [
      w('Invent it', 'Fame', { fame: 4, item: 'cp_rivals_encore_violin' }),
      w('Ring the final chorus instead', 'a legendary bell-instrument', { fame: 2, item: 'cp_bell_final_chorus', flag: 'cp_final_chorus' }),
      w('Steal a rival\'s refrain', 'power, debt', { item: 'cp_applause_eater_lute', flag: 'cp_stolen_refrain' }),
      w('Refuse to perform', 'they boo the System instead', { fame: 2, flag: 'cp_encore_refused' }),
    ], { glyph: '🎻' }),
  clsEv('cp_necro_seventh_funeral_event', 'necromancer', 'swamp', 'Seventh Funeral',
    'Six graves are occupied. The seventh is labeled with your handwriting.', [
      w('Lie down in it briefly', 'a Remain, max HP', { maxHp: -3, item: 'cp_seventh_hero_phylactery', flag: 'cp_seventh_grave' }),
      w('Reap the unplanted grave', 'a cursed harvest', { item: 'cp_corpse_flower_sickle', flag: 'cp_grave_reaped' }),
      w('Fill it with someone already dead', 'taxonomy', { fame: 2, flag: 'cp_grave_filled' }),
      w('Leave it empty', 'the list stays wrong', { fame: 1 }),
    ], { glyph: '⚰️' }),
  clsEv('cp_spellsword_inward_cut', 'spellsword', 'ruins', 'Inward Cut',
    'A practice dummy is stitched from a spell and a sword that disagree.', [
      w('Cut until they agree', 'hybrid blade', { hp: -8, item: 'cp_inward_gate_blade', flag: 'cp_inward_cut' }),
      w('Separate them', 'two lesser pieces', { item: 'cp_spellknife', fame: 1 }),
      w('Leave the argument running', 'it might finish itself', { flag: 'cp_argument_left' }),
    ], { glyph: '⚔️' }),
);

const coop = (id, title, text, choices, extra = {}) => ev({
  id, biome: extra.biome || 'any', title, text, glyph: extra.glyph || '🤝',
  category: extra.cat || 'social', w: 4, tags: ['secret-flag'],
  when: { coop: true }, once: extra.once, family: extra.family,
  identityScope: extra.scope || 'any',
  choices,
});

PACK_EVENTS.push(
  coop('cp_split_gate', 'The Split Gate',
    'The party divides between two rooms with different information. One side chooses the cost; the other chooses the reward. Host-authoritative; both rooms resolve as one atomic outcome.', [
      w('Accept the split', 'asymmetric information, equal expected value', { gold: 20, hp: -6, flag: 'cp_split_accepted', pay: 'actor', receive: 'split' }),
      w('Pay gold to keep the party together', 'sink', { gold: -35, fame: 1, pay: 'party', receive: 'party' }, { req: { gold: 35 } }),
    ], { glyph: '🚪' }),
  coop('cp_one_potion_two_patients', 'One Potion, Two Patients',
    'Two players are injured, but the shrine can heal only one.', [
      w('Use a party potion on one player', 'heal', { useItem: 'potion_s', hpPct: 0.2 }, { req: { item: 'potion_s' } }),
      w('Split the healing inefficiently', 'both get less', { hpPct: 0.08, fame: 1 }),
      w('One player refuses treatment for Fame', 'martyr', { fame: 3, flag: 'cp_refused_heal' }),
      idc({ class: 'priest' }, 'Priest: costly third option', 'HP for both', { hp: -10, hpPct: 0.15 }),
      idc({ class: 'monk' }, 'Monk: costly third option', 'HP for both', { hp: -10, hpPct: 0.15 }),
    ], { biome: 'ruins', glyph: '🧪', cat: 'recovery' }),
  coop('cp_secret_offers', 'Secret Offers',
    'Each player privately receives a different bargain. Consequences are revealed before final confirmation unless secrecy is the theme. Host-authoritative.', [
      w('Take 60 gold; another player loses 8 HP', 'asymmetric', { gold: 60, flag: 'cp_secret_gold', pay: 'none', receive: 'actor', otherPay: 'volunteer', otherCost: { hp: 8 } }),
      w('Gain Fame; another player forfeits the event reward', 'spotlight', { fame: 3, flag: 'cp_secret_fame', pay: 'none', receive: 'actor', otherPay: 'volunteer' }),
      w('Refuse, giving everyone a smaller reward', 'fair', { gold: 15, fame: 1, pay: 'none', receive: 'party' }),
    ], { glyph: '✉️' }),
  coop('cp_volunteers_door', "The Volunteer's Door",
    'One player may lose max HP so everyone receives a gear choice. The volunteer gets first selection or a unique later payoff.', [
      w('Volunteer', 'max HP, first pick', { maxHp: -3, item: 'cp_gate_iron_sword', flag: 'cp_volunteer_gear', pay: 'volunteer', receive: 'volunteer' }),
      w('Pay gold instead', 'no volunteer', { gold: -40, item: 'cp_rootwoven_vest', pay: 'party', receive: 'party' }, { req: { gold: 40 } }),
    ], { biome: 'forest', glyph: '🚪' }),
  coop('cp_pack_exchange', 'Pack Exchange',
    'The dungeon swaps two players\' consumable inventories until the next safe floor. Not mid-combat.', [
      w('Accept', 'floor-scoped swap flag', { flag: 'cp_pack_swapped' }),
      w('Pay gold to prevent it', 'sink', { gold: -30 }, { req: { gold: 30 } }),
      w('Voluntarily trade one item each', 'small swap', { flag: 'cp_pack_partial' }),
      w('Destroy the mechanism for Fame', 'break', { fame: 3, flag: 'cp_pack_broken' }),
    ], { glyph: '🎒' }),
  coop('cp_name_called_first', 'The Name Called First',
    'An NPC credits the entire victory to one party member.', [
      w('That player accepts all Fame', 'spotlight', { fame: 5, flag: 'cp_name_accepted' }),
      w('Divide it', 'split', { fame: 2 }),
      w('Give credit to the lowest-Fame member', 'redistribute', { fame: 3, flag: 'cp_name_lowest' }),
      w('Reject personal glory', 'convert part into a party reward', { fame: 1, hpPct: 0.08 }),
    ], { glyph: '📣' }),
  coop('cp_carried_climber', 'The Carried Climber',
    'One player becomes unable to move without help.', [
      w('Another player takes HP damage to carry them', 'burden', { hp: -10, fame: 2 }),
      w('Spend a potion', 'heal', { useItem: 'potion_s', hpPct: 0.15 }, { req: { item: 'potion_s' } }),
      w('Leave equipment behind to make them lighter', 'offering', { offering: { kinds: ['pack'] } }, { req: { offering: true } }),
      w('Abandon them temporarily only with explicit consent', 'flag', { fame: -3, flag: 'cp_carried_left' }),
    ], { biome: 'swamp', glyph: '🧍' }),
  coop('cp_shared_curse', 'Shared Curse',
    'The party chooses how to divide a curse.', [
      w('One player bears it entirely for a personal reward', 'cursed gear', { item: 'cp_grave_tax_shroud', flag: 'cp_curse_solo' }),
      w('Everyone takes a smaller penalty', 'HP', { hp: -6 }),
      w('Pay gold to seal it', 'sink', { gold: -50 }, { req: { gold: 50 } }),
      w('Transfer it to a chosen item', 'offering', { offering: { kinds: ['pack'] }, flag: 'cp_curse_item' }, { req: { offering: true } }),
    ], { biome: 'ruins', glyph: '☠️' }),
  coop('cp_unequal_treasure', 'Unequal Treasure',
    'Three rewards appear for four players — or one fewer reward than the party size. Never PvP damage.', [
      w('Lowest-gear player chooses first', 'fair-ish', { item: 'cp_ashwood_bow', flag: 'cp_unequal_low' }),
      w('Highest-Fame player chooses', 'spotlight', { item: 'cp_court_rapier', flag: 'cp_unequal_fame' }),
      w('Auction with gold', 'market', { gold: -25, item: 'cp_ruin_repeater' }, { req: { gold: 25 } }),
      w('Destroy all rewards for a party-wide blessing', 'solidarity', { hpPct: 0.1, fame: 2 }),
    ], { glyph: '💎', cat: 'equipment' }),
  coop('cp_absent_players_ghost', "The Absent Player's Ghost",
    'If a teammate is downed or waiting — never merely disconnected — the party encounters a safe narrative echo. Do not make permanent decisions for the absent player.', [
      w('Leave supplies for their return', 'a potion set aside', { consumable: 'cp_pilgrims_ration', flag: 'cp_left_supplies' }),
      w('Take a temporary blessing but owe them gold', 'debt', { hpPct: 0.08, flag: 'cp_owe_absent' }),
      w('Ask the echo for their last known choice', 'information only', { flag: 'cp_echo_asked' }),
    ], { glyph: '👻' }),
  coop('cp_two_hands_lever', 'Two Hands on the Lever',
    'Two players must independently choose Pull or Release. Host resolves the pair atomically.', [
      w('Signal Pull', 'if both pull: reward and HP; mixed: asymmetric', { hp: -6, gold: 25, flag: 'cp_lever_pull' }),
      w('Signal Release', 'if both release: nothing', { flag: 'cp_lever_release' }),
    ], { glyph: '🎚️' }),
  coop('cp_weakest_link', "The Party's Weakest Link",
    'The System publicly identifies a player using a deliberately unfair metric.', [
      w('Defend them', 'lose System favor', { fame: 2, flag: 'cp_defended_weak' }),
      w('Accept the ranking for a reward', 'gold', { gold: 35, fame: -2 }),
      w('Challenge the evaluator', 'combat', { combat: { enemies: ['acolyte'] }, fame: 2 }),
      w('Let the named player take an optional trial', 'personal upgrade', { item: 'cp_unwritten_achievement', flag: 'cp_trial_taken' }),
    ], { glyph: '📉' }),
);

PACK_EVENTS.push(
  ev({ id: 'cp_achievement_cowardice', biome: 'any', category: 'advancement', glyph: '🏅', w: 2, once: true,
    title: 'Achievement Unlocked: Cowardice',
    text: 'The System rewards the party for repeatedly avoiding optional fights. The window is the color of a real achievement. It is still a scene.',
    when: { guards: 8 },
    choices: [
      w('Accept a defensive relic', 'coward\'s prize', { item: 'cp_cowardice_plaque', flag: 'cp_coward_accepted' }),
      w('Reject the label and take a forced challenge', 'fight', { combat: { enemies: ['treant'] }, fame: 2 }),
      w('Spend Fame to rename the achievement', 'Survival Route', { fame: -4, flag: 'cp_renamed_coward', resolveCurse: 'fame_defense' }),
      w('Reveal that survival was the intended heroic route', 'a quieter ending', { fame: 3, flag: 'cp_survival_heroic' }),
    ],
  }),
  ev({ id: 'cp_patch_notes_tomorrow', biome: 'hell', category: 'mystery', glyph: '📄', w: 3, once: true,
    title: 'Patch Notes from Tomorrow',
    text: 'The party discovers future patch notes describing changes to its world.',
    choices: [
      w('Exploit one predicted change for gold', 'gold', { gold: 50, flag: 'cp_patch_exploited' }),
      w('Record an unwritten achievement instead', 'the ledger notices', { item: 'cp_unwritten_achievement', flag: 'cp_unwritten_taken' }),
      w('Prevent a listed NPC removal', 'Fame', { fame: 4, flag: 'cp_npc_preserved' }),
      w('Preserve a soon-to-be-weakened item', 'flag', { flag: 'cp_item_preserved' }),
      w('Give the notes to the administrator fragment', 'evidence', { flag: 'cp_notes_to_admin' }),
      w('Burn them to protect the timeline', 'ash', { fame: 2, flag: 'cp_notes_burned2' }),
    ],
  }),
  ev({ id: 'cp_inventory_teammate', biome: 'hell', category: 'dangerous', glyph: '🎒', w: 3, once: true,
    title: 'Inventory Item: "A Teammate"',
    text: 'A corrupted window lists one party member as tradeable equipment. Co-op response depends on the named player\'s choice. Disconnect is never this condition.',
    choices: [
      w('Close the window', 'you refuse the metaphor', { fame: 2, flag: 'cp_window_closed', resolveCurse: 'unequip_wielder' }),
      w('Inspect its impossible stats', 'a prison memory, and a listing that names you', { flag: 'cp_prison_memory', item: 'cp_blade_lists_you', world: { knowledge: 'cp_listed_person' } }),
      w('Attempt to unequip them', 'you cannot; a memory opens', { flag: 'cp_unequip_failed' }),
      w('Sell the listing — not the person — for counterfeit System currency', 'fake gold', { gold: 40, flag: 'cp_sold_listing' }),
    ],
  }),
  ev({ id: 'cp_fame_limit_exceeded', biome: 'hell', category: 'advancement', glyph: '⭐', w: 2, once: true,
    title: 'Fame Limit Exceeded',
    text: 'At high Fame, the System can no longer reconcile the party\'s reputation.',
    when: { fame: 18 },
    choices: [
      w('Convert excess Fame into gold', 'capped conversion', { fame: -8, gold: 60 }),
      w('Convert it into a boss challenge', 'fight', { combat: { enemies: ['void_eye'] }, fame: -4 }),
      w('Distribute it among forgotten NPCs', 'they remember you', { fame: -6, flag: 'cp_fame_distributed' }),
      w('Let the System create an exaggerated hostile version of the party', 'echo fight', { combat: { enemies: ['dusk_lurker'] }, flag: 'cp_fame_echo' }),
    ],
  }),
  ev({ id: 'cp_gate_leading_home', biome: 'hell', category: 'dangerous', glyph: '🏠', w: 2, once: true,
    title: 'The Gate Leading Home',
    text: 'A convincing exit appears before the climb is complete. Leaving is a bittersweet ending flag, not a save restore.',
    choices: [
      w('Leave and receive a bittersweet ending', 'run-end flag (host-authoritative)', { flag: 'cp_went_home', fame: 2 }),
      w('Test the gate with a potion or item', 'it is another layer', { useItem: 'potion_s', flag: 'cp_home_tested' }, { req: { item: 'potion_s' } }),
      w('Send an NPC through', 'if you have one', { flag: 'cp_npc_through' }),
      w('Destroy it for Fame', 'no door', { fame: 4, flag: 'cp_home_destroyed' }),
      w('Discover that home is another dungeon layer', 'the climb continues', { flag: 'cp_home_is_layer', world: { knowledge: 'cp_home_layer' } }),
    ],
  }),
  ev({ id: 'cp_throne_empty_sheet', biome: 'hell', category: 'advancement', glyph: '📜', w: 2, once: true,
    title: "The Throne's Empty Character Sheet",
    text: 'The throne displays the ruler\'s stats, but the name and class are blank.',
    when: { floorMin: 48 },
    choices: [
      w('Insert the active character\'s name', 'you', { flag: 'cp_throne_self', item: 'cp_thrones_blank_sheet' }),
      w('Insert a dead or sacrificed NPC\'s name', 'their story', { flag: 'cp_throne_npc' }),
      w('Insert the party name', 'together', { flag: 'cp_throne_party' }),
      w('Leave it blank and reject the throne', 'no ruler', { flag: 'cp_throne_blank', fame: 3 }),
      w('Hidden class: write a name the System previously erased', 'if you know it', { flag: 'cp_throne_erased' }),
    ],
  }),
  ev({ id: 'cp_final_merchant', biome: 'hell', category: 'merchant', glyph: '🛒', w: 2, once: true,
    title: 'The Final Merchant',
    text: 'A merchant offers to buy resources that normally have no cash value.',
    when: { floorMin: 45 },
    choices: [
      w('Sell remaining potions', 'if you have them', { useItem: 'potion_s', gold: 40 }),
      w('Sell Fame', 'name for coin', { fame: -8, gold: 70 }, { req: { fame: 8 } }),
      w('Sell max HP', 'blood price', { maxHp: -6, gold: 80 }),
      w('Sell one completed chain flag', 'erasing its ending', { flag: 'cp_ending_sold', gold: 50 }),
      w('Buy back a previously sacrificed object at an extreme price', 'if you have the flag', { gold: -120, item: 'cp_kiln_memory_slag' }, { req: { gold: 120 } }),
    ],
  }),
  ev({ id: 'cp_dungeon_asks_who', biome: 'hell', category: 'advancement', glyph: '❓', w: 2, once: true,
    title: 'The Dungeon Asks Who the Story Was About',
    text: 'The final narrative reckoning checks accumulated flags. The selected answer alters the epilogue flag, not simple gold.',
    when: { floorMin: 50 },
    choices: [
      w('The strongest climber', 'solo myth', { flag: 'cp_story_strongest' }),
      w('The party', 'together', { flag: 'cp_story_party' }),
      w('The people rescued along the way', 'their names', { flag: 'cp_story_rescued' }),
      w('The kingdom beneath the dungeon', 'the drowned court', { flag: 'cp_story_kingdom' }),
      w('The rival who never reached the throne', 'their fire', { flag: 'cp_story_rival' }),
      w('The System itself', 'it wanted a witness', { flag: 'cp_story_system' }),
      w('Nobody — the story is still being written', 'open ending', { flag: 'cp_story_nobody', fame: 2 }),
    ],
  }),
);

export { PACK_EVENTS };
