import { relic, ef } from './helpers.js';

export const PACK_RELICS = [
  relic({ id: 'cp_backward_gate_hinge', name: 'Backward Gate Hinge', rarity: 'rare', quest: true,
    desc: 'Once per biome, exchange an event HP cost for gold or a gold cost for HP.',
    effects: [ef('onEventResolve', 'convertResource', { stat: 'hp', target: 'gold', amount: 1 })] }),
  relic({ id: 'cp_seventh_nameplate', name: 'Seventh Nameplate', rarity: 'uncommon',
    desc: 'Unrecognized or low-Fame characters gain stronger rescue rewards.',
    effects: [ef('onEventResolve', 'gainFame', { amount: 1, when: { fameBelow: 8 } })] }),
  relic({ id: 'cp_provisional_hero_badge', name: 'Provisional Hero Badge', rarity: 'epic',
    desc: 'Spend Fame in place of part of one merchant or bureaucracy fee (mutex vs other substitutions).',
    mutex: 'resource_substitution',
    effects: [ef('onEventResolve', 'spendFamePower', { fame: 2, mult: 1 })] }),
  relic({ id: 'cp_crimson_crystal_shard', name: 'Crimson Crystal Shard', rarity: 'legendary', mutex: 'lethal_ward', quest: true,
    desc: 'One-time lethal ward with a permanent max-HP cost. Not a save-file restore.',
    effects: [ef('beforeDamageTaken', 'lethalWard', { mutex: 'lethal_ward', maxHp: -4, once: 'run' })] }),
  relic({ id: 'cp_portrait_previous_party', name: 'Portrait of the Previous Party', rarity: 'rare',
    desc: 'Reveals one likely enemy action shape at combat start.',
    effects: [ef('onCombatStart', 'revealIntent', { value: 'shape', once: 'combat' })] }),
  relic({ id: 'cp_last_companions_bell', name: "Last Companion's Bell", rarity: 'unique', unique: true, quest: true, acquisition: 'unique',
    desc: 'UNIQUE · protecting the lowest-health ally arms a heavier next hit and shares a sliver of the heal.',
    effects: [
      ef('onDamageTaken', 'armNextHit', { add: 7 }),
      ef('onHeal', 'shareHeal', { pct: 0.15 }),
    ] }),
  relic({ id: 'cp_empty_saint_icon', name: 'Empty Saint Icon', rarity: 'uncommon',
    desc: 'The first character healed each combat receives a distinct blessing.',
    effects: [ef('onHeal', 'heal', { amount: 5, once: 'combat' })] }),
  relic({ id: 'cp_gate_beast_eggshell', name: 'Gate-Beast Eggshell', rarity: 'uncommon',
    desc: 'Potions gain a minor random creature property (bounded rider).',
    effects: [ef('onConsumable', 'statusChance', { status: 'burn', chance: 0.2 })] }),
  relic({ id: 'cp_ring_seven_owners', name: 'Ring of Seven Owners', rarity: 'legendary', quest: true,
    desc: 'Every seventh different technique gains a bonus.',
    effects: [ef('onSkillUse', 'addCounter', { key: 'sevenTech', scope: 'run', when: { differentFromPrior: true } }),
      ef('onHit', 'modDamage', { add: 7, when: { counter: 'sevenTech', counterAt: 7 } })] }),
  relic({ id: 'cp_redacted_support_ticket', name: 'Redacted Support Ticket', rarity: 'epic', quest: true,
    desc: 'Cancel one System-imposed event penalty per run.',
    effects: [ef('onEventResolve', 'cancelEventPenalty')] }),
  relic({ id: 'cp_receipt_from_tomorrow', name: 'Receipt from Tomorrow', rarity: 'epic', quest: true,
    desc: 'Reserve one shop item and purchase it later at its original price.',
    playable: 'adapted', adaptation: 'First shop purchase stores a receipt; the next purchase is 20% off (capped with other discounts).',
    effects: [ef('onShopAction', 'storeMemory', { key: 'reservedShop', scope: 'run' })] }),
  relic({ id: 'cp_fame_eater_tooth_relic', name: 'Fame-Eater Tooth', rarity: 'rare',
    desc: 'Convert Fame into a temporary combat buff at campfires.',
    effects: [ef('onCampfire', 'spendFamePower', { fame: 3, mult: 1.2 })] }),
  relic({ id: 'cp_drowned_crown_fragment', name: 'Drowned Crown Fragment', rarity: 'epic', quest: true,
    desc: 'Royal and court events expose additional choices.',
    effects: [ef('onEventResolve', 'setFlag', { key: 'crownFragment', scope: 'run', persistFlag: true })] }),
  relic({ id: 'cp_gate_mason_plumb', name: "Gate Mason's Plumb Line", rarity: 'rare',
    desc: 'Reduces the risk of shortcuts and unstable gates.',
    effects: [ef('onFloorStart', 'armNextIncoming', { mult: 0.88, scope: 'floor' })] }),
  relic({ id: 'cp_ashen_rival_ember', name: "Ashen Rival's Ember", rarity: 'uncommon',
    desc: 'Gains power when another party member uses a different class technique.',
    effects: [ef('onHit', 'modDamage', { add: 2, when: { differentFromPrior: true } })] }),
  relic({ id: 'cp_bottle_of_applause', name: 'Bottle of Applause', rarity: 'uncommon',
    desc: 'Stores excess Fame, which can later be released or sold (run-scoped counter).',
    effects: [ef('onEventResolve', 'addCounter', { key: 'bottledFame', scope: 'run' })] }),
  relic({ id: 'cp_unminted_coin', name: 'Unminted Coin', rarity: 'common',
    desc: 'Counts as gold only during events, not shops.',
    effects: [ef('onEventResolve', 'convertResource', { key: 'unminted' })] }),
  relic({ id: 'cp_broken_boss_telegraph', name: 'Broken Boss Telegraph', rarity: 'rare',
    desc: 'Once per combat, reveal whether a charged intent is single-target or AOE before normal disclosure.',
    effects: [ef('onIntentRevealed', 'revealIntent', { value: 'shape', once: 'combat' })] }),
  relic({ id: 'cp_kiln_memory_slag', name: 'Kiln Memory Slag', rarity: 'common',
    desc: 'Sacrificed items contribute slightly more value to reforging.',
    effects: [ef('onEventResolve', 'convertResource', { key: 'kiln' })] }),
  relic({ id: 'cp_moss_chapel_candle', name: 'Moss Chapel Candle', rarity: 'common',
    desc: 'Resource conversions at shrines become more efficient.',
    effects: [ef('onEventResolve', 'convertResource', { amount: 1 })] }),
  relic({ id: 'cp_frozen_wedding_ring', name: 'Frozen Wedding Ring', rarity: 'rare', quest: true,
    desc: 'Healing a different ally on consecutive turns strengthens both.',
    effects: [ef('onHeal', 'shareHeal', { pct: 0.2 })] }),
  relic({ id: 'cp_cowardice_plaque', name: 'Plaque of Intended Survival', rarity: 'uncommon',
    desc: 'A defensive relic for walking away. Once per combat, the first hit is softer.',
    effects: [ef('beforeDamageTaken', 'modIncoming', { mult: 0.85, once: 'combat' })] }),
  relic({ id: 'cp_frogs_hero_license', name: "Frog's Hero License", rarity: 'uncommon',
    desc: 'Treat Fame as one rank higher for event eligibility.',
    effects: [ef('onEventResolve', 'setFlag', { key: 'fameBoost', scope: 'run', persistFlag: true })] }),
  relic({ id: 'cp_demon_queue_token', name: "Demon's Queue Token", rarity: 'epic',
    desc: 'Skip one forced encounter but lose its reward.',
    playable: 'adapted', adaptation: 'Negates the first incoming hit of the next combat and spends 12 gold once per run.',
    effects: [
      ef('onCombatStart', 'armNextIncoming', { id: 'queueSkipIn', mult: 0, once: 'run' }),
      ef('onCombatStart', 'spendGoldPower', { id: 'queueSkipGold', gold: 12, mult: 1, once: 'run' }),
    ] }),
  relic({ id: 'cp_counterfeit_halo', name: 'Counterfeit Halo', rarity: 'rare',
    desc: 'Negative Fame requirements are easier; positive-Fame rewards weaken.',
    effects: [
      ef('onEventResolve', 'setFlag', { key: 'counterfeitHalo', scope: 'run', persistFlag: true }),
      ef('onEventResolve', 'convertResource', { key: 'halo' }),
    ] }),
  relic({ id: 'cp_gate_surveyor_last_report', name: "Gate Surveyor's Last Report", rarity: 'rare',
    desc: 'Reveals the broad category of the next unresolved floor.',
    effects: [ef('onFloorStart', 'revealIntent', { value: 'category' })] }),
  relic({ id: 'cp_corpse_flower_seed', name: 'Corpse-Flower Seed', rarity: 'uncommon',
    desc: 'The first defeated enemy each combat grows a biome-dependent bloom.',
    effects: [ef('onKill', 'heal', { pct: 0.04, once: 'combat' })] }),
  relic({ id: 'cp_invisible_toll_receipt', name: 'Invisible Toll Receipt', rarity: 'common',
    desc: 'Refunds a limited portion of purse-scaled event tolls.',
    effects: [ef('onEventResolve', 'gainGold', { amount: 5, once: 'floor' })] }),
  relic({ id: 'cp_mirror_splinter', name: 'Mirror Splinter', rarity: 'rare',
    desc: 'Copy one modest equipment property while accepting one of its drawbacks (campfire).',
    effects: [ef('onCampfire', 'storeMemory', { key: 'mirrorProp', scope: 'run' })] }),
  relic({ id: 'cp_monsters_true_name', name: "Monster's True Name", rarity: 'rare',
    desc: 'Choose an enemy family; deal more damage to it but receive less gold from it.',
    effects: [ef('onHit', 'modDamage', { vsFamily: 'wolf', mult: 1.12 })] }),
  relic({ id: 'cp_refugee_camp_banner', name: 'Refugee Camp Banner', rarity: 'uncommon',
    desc: 'Rescue choices provide stronger Fame and occasional supplies.',
    effects: [ef('onEventResolve', 'gainFame', { amount: 1 })] }),
  relic({ id: 'cp_administrators_bent_key', name: "Administrator's Bent Key", rarity: 'epic',
    desc: 'Opens corrupted System choices but increases audit encounters.',
    effects: [ef('onEventResolve', 'setFlag', { key: 'bentKey', scope: 'run', persistFlag: true })] }),
  relic({ id: 'cp_unwritten_achievement', name: 'The Unwritten Achievement', rarity: 'wrld', wrld: true, exclusive: true, acquisition: 'wrld',
    desc: 'WRLD · the tower writes unusual deeds into canon. Unusual event resolutions stack; the seventh permanently arms your hits. There is only one.',
    allStats: 2, xpMult: 1.2, fameGainMult: 1.25,
    effects: [
      ef('onEventResolve', 'addCounter', { key: 'unusual', scope: 'run' }),
      ef('onHit', 'modDamage', { add: 2, when: { counter: 'unusual' } }),
      ef('onHit', 'modDamage', { add: 5, when: { counter: 'unusual', counterAt: 7 } }),
    ] }),
  relic({ id: 'cp_empty_inventory_slot', name: 'Empty Inventory Slot', rarity: 'uncommon',
    desc: 'Grants power while deliberately leaving one gear slot empty.',
    effects: [ef('onHit', 'modDamage', { add: 2, emptySlots: true })] }),
  relic({ id: 'cp_hoards_first_coin', name: "Hoard's First Coin", rarity: 'rare', quest: true,
    desc: 'Improves gold-based effects but cannot itself be spent.',
    effects: [ef('onHit', 'modDamage', { add: 1, when: { goldAtLeast: 20 } })] }),
  relic({ id: 'cp_chain_shared_burdens', name: 'Chain of Shared Burdens', rarity: 'rare',
    desc: 'A portion of single-target healing is shared with the lowest-health ally.',
    effects: [ef('onHeal', 'shareHeal', { pct: 0.3 })] }),
  relic({ id: 'cp_thrones_blank_sheet', name: "Throne's Blank Character Sheet", rarity: 'unique', unique: true, quest: true, acquisition: 'unique', allStats: 1,
    desc: 'UNIQUE · evolves according to the run\'s dominant class, bloodline, and moral flags. One sheet per climber.',
    effects: [ef('onCombatEnd', 'evolveItem', { itemId: 'cp_thrones_blank_sheet' })] }),
];
