import { technique, ef } from './helpers.js';

function kit(cls, rows) {
  return rows.map(r => technique({ class: cls, ...r }));
}

export const PACK_SKILLS = Object.fromEntries([
  ...kit('warrior', [
    { id: 'cp_intercepting_step', name: 'Intercepting Step', charge: 0, target: 'self', fx: 'buff',
      desc: 'Free defensive technique. Redirect part of an ally\'s next single-target hit.',
      effects: [ef('onSkillUse', 'redirectDamage', { pct: 0.35, mutex: 'damage_redirect' })] },
    { id: 'cp_shieldbreaker_rhythm', name: 'Shieldbreaker Rhythm', charge: 0, power: 90, stat: 'str', fx: 'blunt',
      desc: 'Free attack. Modest damage that exposes shielded enemies.',
      effects: [ef('onHit', 'modDamage', { vsShielded: 1.2 })] },
    { id: 'cp_gatebreaker_charge', name: 'Gatebreaker Charge', charge: 1, cooldown: 1, power: 120, stat: 'str', fx: 'slash',
      desc: 'Heavy strike that deals additional damage to a charging enemy.',
      effects: [ef('onHit', 'modDamage', { vsCharging: 1.25 })] },
    { id: 'cp_bell_bearers_oath', name: "Bell-Bearer's Oath", charge: 1, cooldown: 2, target: 'self', fx: 'buff',
      desc: 'Choose an ally; damage taken for them empowers the next attack.',
      effects: [
        ef('onSkillUse', 'redirectDamage', { pct: 0.3, mutex: 'damage_redirect' }),
        ef('onSkillUse', 'armNextHit', { add: 6 }),
      ] },
    { id: 'cp_hold_the_world_shut', name: 'Hold the World Shut', charge: 2, cooldown: 3, target: 'self', fx: 'buff',
      desc: 'Greatly reduces one incoming AOE but damages the Warrior.',
      effects: [ef('onSkillUse', 'interceptAoe', { pct: 0.55, mutex: 'damage_redirect' })] },
    { id: 'cp_sevenfold_verdict', name: 'Sevenfold Verdict', charge: 3, cooldown: 3, power: 150, stat: 'str', fx: 'slash',
      desc: 'Finisher whose rider depends on Guard, intercept, basic attack, or execution used this combat.',
      effects: [
        ef('onHit', 'modDamage', { add: 5, when: { flag: 'behaveGuard' } }),
        ef('onHit', 'modDamage', { add: 5, when: { flag: 'behaveIntercept' } }),
        ef('onHit', 'modDamage', { add: 5, when: { flag: 'behaveBasic' } }),
        ef('onHit', 'modDamage', { add: 5, when: { flag: 'behaveExec' } }),
      ] },
  ]),
  ...kit('mage', [
    { id: 'cp_margin_spark', name: 'Margin Spark', charge: 0, power: 80, stat: 'int', fx: 'arcane',
      desc: 'Free spell. Changes element based on the previous spell used.',
      effects: [ef('onHit', 'modDamage', { add: 2, when: { differentFromPrior: true } })] },
    { id: 'cp_prepared_annotation', name: 'Prepared Annotation', charge: 0, target: 'self', fx: 'buff',
      desc: 'Free utility. Store a modest spell modifier for next turn.',
      effects: [ef('onSkillUse', 'armNextHit', { add: 5, scope: 'combat' })] },
    { id: 'cp_gate_fold', name: 'Gate Fold', charge: 1, cooldown: 1, target: 'one', power: 70, stat: 'int', fx: 'arcane',
      desc: 'Redirect or retarget a non-signature enemy action (bounded).',
      effects: [ef('onSkillUse', 'weakenIntent', { mult: 0.8 })] },
    { id: 'cp_borrowed_element', name: 'Borrowed Element', charge: 1, cooldown: 2, target: 'self', fx: 'buff',
      desc: 'Gain a temporary element with an attached vulnerability.',
      effects: [
        ef('onSkillUse', 'armNextHit', { add: 4, mult: 1.12 }),
        ef('onSkillUse', 'armNextIncoming', { add: 3 }),
      ] },
    { id: 'cp_patch_from_tomorrow', name: 'Patch from Tomorrow', charge: 2, cooldown: 3, target: 'self', fx: 'buff',
      desc: 'Upgrade one spell for this combat while weakening another.',
      effects: [
        ef('onSkillUse', 'armNextHit', { mult: 1.25 }),
        ef('onSkillUse', 'armNextIncoming', { mult: 1.1 }),
      ] },
    { id: 'cp_paradox_load', name: 'Paradox Load', charge: 3, cooldown: 3, power: 90, stat: 'int', fx: 'arcane',
      desc: 'Recast two different previously used spells at reduced strength (depth 1).',
      effects: [ef('onSkillUse', 'echoAction', { mult: 0.45, capability: 'echo_copy' })] },
  ]),
  ...kit('archer', [
    { id: 'cp_mark_the_uncounted', name: 'Mark the Uncounted', charge: 0, target: 'one', power: 40, stat: 'dex', fx: 'pierce',
      desc: 'Establish a mark that persists through transformations (family id).',
      effects: [ef('onHit', 'markTarget')] },
    { id: 'cp_three_trails', name: 'Three Trails', charge: 0, target: 'self', fx: 'buff',
      desc: 'Free stance: Hunt for damage, Rescue for ally support, Escape for defense.',
      effects: [ef('onSkillUse', 'chooseStance', { stance: 'cycle' })] },
    { id: 'cp_scent_tomorrow', name: 'Scent Tomorrow', charge: 1, cooldown: 1, target: 'one', power: 90, stat: 'dex', fx: 'pierce',
      desc: 'Reveal intent and improve the next attack against that enemy.',
      effects: [ef('onSkillUse', 'revealIntent', { value: 'shape' }), ef('onHit', 'modDamage', { mult: 1.15 })] },
    { id: 'cp_spinebow_volley', name: 'Spinebow Volley', charge: 1, cooldown: 2, power: 85, stat: 'dex', fx: 'pierce',
      desc: 'Hits the marked target harder (bounded; not a free AOE).',
      effects: [ef('onHit', 'modDamage', { when: { targetMarked: true }, mult: 1.25 })] },
    { id: 'cp_avalanche_calculation', name: 'Avalanche Calculation', charge: 2, cooldown: 2, power: 110, stat: 'dex', fx: 'pierce',
      desc: 'Damage increases for every distinct target previously attacked.',
      effects: [ef('onHit', 'addCounter', { key: 'distinct', scope: 'combat' }), ef('onHit', 'modDamage', { add: 3 })] },
    { id: 'cp_horizon_gate', name: 'Horizon Gate', charge: 3, cooldown: 3, power: 160, stat: 'dex', fx: 'pierce',
      desc: 'Massive precision shot whose effect changes with the active Trail.',
      effects: [
        ef('onHit', 'modDamage', { mult: 1.22, when: { stance: 'hunt' } }),
        ef('onHit', 'heal', { amount: 8, when: { stance: 'rescue' } }),
        ef('onHit', 'modDamage', { mult: 0.9, when: { stance: 'escape' } }),
        ef('onSkillUse', 'armNextIncoming', { mult: 0.75, when: { stance: 'escape' } }),
      ] },
  ]),
  ...kit('rogue', [
    { id: 'cp_invisible_toll', name: 'Invisible Toll', charge: 0, power: 85, stat: 'dex', fx: 'slash',
      desc: 'Removes a small portion of a buff or shield.',
      effects: [ef('onHit', 'modDamage', { vsShielded: 1.15 })] },
    { id: 'cp_false_receipt', name: 'False Receipt', charge: 0, target: 'one', fx: 'buff',
      desc: 'Mark one enemy benefit as unpaid.',
      effects: [ef('onSkillUse', 'applyStatus', { status: 'marked', turns: 3 })] },
    { id: 'cp_counterfeit_turn', name: 'Counterfeit Turn', charge: 1, cooldown: 1, power: 70, stat: 'dex', fx: 'slash',
      desc: 'Act with reduced power immediately after an ally (not an extra turn).',
      effects: [ef('onHit', 'modDamage', { mult: 0.85 })] },
    { id: 'cp_steal_intent', name: 'Steal Intent', charge: 1, cooldown: 2, target: 'one', power: 60, stat: 'dex', fx: 'slash',
      desc: 'Weaken an enemy action and turn part of it into a Rogue buff.',
      effects: [ef('onSkillUse', 'weakenIntent', { mult: 0.8 })] },
    { id: 'cp_echo_feint', name: 'Echo Feint', charge: 2, cooldown: 2, power: 80, stat: 'dex', fx: 'slash',
      desc: 'Repeat the prior basic attack against a different target (depth 1).',
      effects: [ef('onSkillUse', 'echoAction', { mult: 0.5, capability: 'echo_copy' })] },
    { id: 'cp_final_audit', name: 'Final Audit', charge: 3, cooldown: 3, power: 145, stat: 'dex', fx: 'slash',
      desc: 'Collect damage based on removed buffs, unpaid marks, and enemy charge.',
      effects: [ef('onHit', 'modDamage', { vsCharging: 1.2, vsStatus: 'marked', mult: 1.15 })] },
  ]),
  ...kit('priest', [
    { id: 'cp_name_the_wounded', name: 'Name the Wounded', charge: 0, target: 'self', fx: 'heal', healPct: 0.08,
      desc: 'Free heal. Records the target for later miracles.',
      effects: [ef('onHeal', 'recordName')] },
    { id: 'cp_merciful_judgment', name: 'Merciful Judgment', charge: 0, power: 90, stat: 'wis', fx: 'holy',
      desc: 'Stronger against an enemy the Priest previously spared or healed.',
      effects: [ef('onHit', 'modDamage', { add: 6, when: { flag: 'named:self' } })] },
    { id: 'cp_reliquary_transfer', name: 'Reliquary Transfer', charge: 1, cooldown: 1, target: 'self', fx: 'buff',
      desc: 'Move a negative status or part of an injury onto the Priest.',
      effects: [ef('onSkillUse', 'redirectDamage', { pct: 0.3, mutex: 'damage_redirect' })] },
    { id: 'cp_heretic_miracle', name: 'Heretic Miracle', charge: 1, cooldown: 2, target: 'self', fx: 'heal', healPct: 0.12,
      desc: 'Heal an enemy or sacrifice HP to create a stronger party blessing.',
      effects: [ef('onSkillUse', 'heal', { pct: 0.08 })] },
    { id: 'cp_canonize', name: 'Canonize', charge: 2, cooldown: 3, target: 'self', fx: 'buff',
      desc: 'Give an ally a saintly role based on their class.',
      effects: [
        ef('onSkillUse', 'heal', { amount: 8 }),
        ef('onSkillUse', 'armNextHit', { add: 4 }),
        ef('onSkillUse', 'overhealWard'),
      ] },
    { id: 'cp_last_rite_nameless', name: 'Last Rite of the Nameless', charge: 3, cooldown: 3, target: 'self', fx: 'heal', healPct: 0.22,
      desc: 'Major heal, ward, or judgment determined by who has fallen or reached critical HP.',
      effects: [ef('onSkillUse', 'overhealWard'), ef('onSkillUse', 'heal', { pct: 0.1 })] },
  ]),
  ...kit('monk', [
    { id: 'cp_alternating_palm', name: 'Alternating Palm', charge: 0, power: 95, stat: 'dex', fx: 'blunt',
      desc: 'Stronger when different from the prior action.',
      effects: [ef('onHit', 'modDamage', { mult: 1.14, when: { differentFromPrior: true } })] },
    { id: 'cp_listen_to_the_floor', name: 'Listen to the Floor', charge: 0, target: 'self', fx: 'buff',
      desc: 'Prepare to counter the next repeated enemy behavior.',
      effects: [
        ef('onSkillUse', 'revealIntent', { value: 'shape' }),
        ef('onSkillUse', 'armNextIncoming', { mult: 0.82 }),
      ] },
    { id: 'cp_borrowed_wound', name: 'Borrowed Wound', charge: 1, cooldown: 1, target: 'self', fx: 'buff',
      desc: 'Take part of an ally\'s damage and convert it into Flow.',
      effects: [ef('onSkillUse', 'redirectDamage', { pct: 0.3, mutex: 'damage_redirect' })] },
    { id: 'cp_gate_carrying_form', name: 'Gate-Carrying Form', charge: 1, cooldown: 2, target: 'self', fx: 'buff',
      desc: 'Protect allies while accumulating Burden.',
      effects: [
        ef('onSkillUse', 'redirectDamage', { pct: 0.3, mutex: 'damage_redirect' }),
        ef('onSkillUse', 'armNextIncoming', { add: 2 }),
      ] },
    { id: 'cp_seven_breaths', name: 'Seven Breaths', charge: 2, cooldown: 2, power: 100, stat: 'dex', fx: 'blunt',
      desc: 'Spend Flow on a configurable sequence of attack, defense, and healing (bounded).',
      effects: [ef('onHit', 'heal', { amount: 6 }), ef('onHit', 'modDamage', { add: 2 })] },
    { id: 'cp_silence_the_system', name: 'Silence the System', charge: 3, cooldown: 3, target: 'one', power: 80, stat: 'wis', fx: 'arcane',
      desc: 'Temporarily suppress enemy status riders or a non-signature special property.',
      effects: [ef('onSkillUse', 'weakenIntent', { mult: 0.7 })] },
  ]),
  ...kit('bard', [
    { id: 'cp_improvised_chorus', name: 'Improvised Chorus', charge: 0, target: 'self', fx: 'buff',
      desc: 'Copies the broad category of the previous ally action.',
      effects: [ef('onSkillUse', 'copySupport', { mult: 0.5, capability: 'echo_copy' })] },
    { id: 'cp_refrain_of_recognition', name: 'Refrain of Recognition', charge: 0, target: 'self', fx: 'buff',
      desc: 'Gain or distribute a small Fame-based buff.',
      effects: [ef('onSkillUse', 'gainFame', { amount: 1 })] },
    { id: 'cp_rivals_encore', name: "Rival's Encore", charge: 1, cooldown: 1, target: 'self', fx: 'buff',
      desc: 'Repeat an ally\'s last support effect at reduced potency (depth 1).',
      effects: [ef('onSkillUse', 'copySupport', { mult: 0.6, capability: 'echo_copy' })] },
    { id: 'cp_gate_queue_march', name: 'Gate-Queue March', charge: 1, cooldown: 2, target: 'self', fx: 'buff',
      desc: 'Small initiative flag for upcoming ally actions (no extra turns).',
      playable: 'adapted', adaptation: 'Does not rewrite turn order; grants Battle Charge as initiative.',
      effects: [ef('onSkillUse', 'grantCharge', { amount: 1 })] },
    { id: 'cp_ballad_false_hero', name: 'Ballad of the False Hero', charge: 2, cooldown: 2, power: 90, stat: 'lk', fx: 'arcane',
      desc: 'Stronger for low-Fame or debuffed allies.',
      effects: [ef('onHit', 'modDamage', { mult: 1.12, when: { fameBelow: 8 } })] },
    { id: 'cp_name_everyone', name: 'Name Everyone', charge: 3, cooldown: 3, target: 'self', fx: 'heal', healPct: 0.1,
      desc: 'Party-wide crescendo whose effects depend on each ally\'s class (normalized flags).',
      effects: [ef('onSkillUse', 'heal', { pct: 0.08 }), ef('onSkillUse', 'overhealWard')] },
  ]),
  ...kit('necromancer', [
    { id: 'cp_gather_remains', name: 'Gather Remains', charge: 0, target: 'self', fx: 'buff',
      desc: 'Convert a defeated enemy or summon into a typed Remain (allowlisted).',
      effects: [ef('onSkillUse', 'storeArchetype')] },
    { id: 'cp_grave_tax_bolt', name: 'Grave-Tax Bolt', charge: 0, power: 85, stat: 'int', fx: 'arcane',
      desc: 'Generates Death Debt when it finishes a target.',
      effects: [ef('onKill', 'addCounter', { key: 'deathDebt', scope: 'combat' })] },
    { id: 'cp_footnote_resurrection', name: 'Footnote Resurrection', charge: 1, cooldown: 2, target: 'self', fx: 'buff',
      desc: 'Create a temporary echo of a defeated summon or minor enemy (safe allowlist, cap 2).',
      effects: [ef('onSkillUse', 'summonAlly', { archetype: 'skeleton', capability: 'summon' })] },
    { id: 'cp_corpse_flower_cultivation', name: 'Corpse-Flower Cultivation', charge: 1, cooldown: 2, power: 70, stat: 'int', fx: 'arcane',
      desc: 'Grow a bloom based on the target\'s statuses at death.',
      effects: [ef('onKill', 'heal', { pct: 0.05 })] },
    { id: 'cp_unlived_injury', name: 'Unlived Injury', charge: 2, cooldown: 3, power: 100, stat: 'int', fx: 'arcane',
      desc: 'Apply damage that becomes real when the enemy acts (delayed, bounded).',
      effects: [ef('onHit', 'delayEffect', { delayTurns: 1, add: 8 })] },
    { id: 'cp_seventh_funeral', name: 'Seventh Funeral', charge: 3, cooldown: 3, target: 'self', fx: 'buff',
      desc: 'Consume accumulated Remains for a configurable summon, heal, or curse.',
      effects: [ef('onSkillUse', 'summonAlly', { archetype: 'leech', capability: 'summon' }),
        ef('onSkillUse', 'heal', { pct: 0.1 })] },
  ]),
  ...kit('spellsword', [
    { id: 'cp_spellweave_cut', name: 'Spellweave Cut', charge: 0, power: 95, stat: 'str+int', fx: 'slash',
      desc: 'Changes rider based on the last spell used.',
      effects: [ef('onHit', 'modDamage', { add: 2, when: { differentFromPrior: true } })] },
    { id: 'cp_edge_cantrip', name: 'Edge Cantrip', charge: 0, target: 'self', fx: 'buff',
      desc: 'Prepares the next weapon attack.',
      effects: [ef('onSkillUse', 'armNextHit', { add: 5 })] },
    { id: 'cp_gate_fold_slash', name: 'Gate-Fold Slash', charge: 1, cooldown: 1, power: 110, stat: 'str+int', fx: 'slash',
      desc: 'Hybrid strike that changes damage type mid-action (bounded).',
      effects: [ef('onHit', 'modDamage', { mult: 1.1 })] },
    { id: 'cp_mirror_exchange', name: 'Mirror Exchange', charge: 1, cooldown: 2, power: 70, stat: 'int', fx: 'arcane',
      desc: 'Trade one status with the target.',
      effects: [ef('onHit', 'convertStatus', { status: 'weaken', statusTo: 'frail' })] },
    { id: 'cp_counterspell_lunge', name: 'Counterspell Lunge', charge: 2, cooldown: 2, power: 120, stat: 'str', fx: 'slash',
      desc: 'Weaken a charged magical intent and immediately attack.',
      effects: [ef('onHit', 'weakenIntent', { mult: 0.8 }), ef('onHit', 'modDamage', { vsCharging: 1.15 })] },
    { id: 'cp_inward_horizon', name: 'Inward Horizon', charge: 3, cooldown: 3, power: 140, stat: 'str+int', fx: 'slash',
      desc: 'A physical strike and spell detonation whose order depends on the prior two actions.',
      effects: [ef('onHit', 'echoAction', { mult: 0.4, capability: 'echo_copy' })] },
  ]),
  ...kit('warlock', [
    { id: 'cp_clause_spark', name: 'Clause Spark', charge: 0, power: 85, stat: 'int', fx: 'arcane',
      desc: 'Free bolt that writes a small hex.',
      effects: [ef('onHit', 'statusChance', { status: 'hexed', chance: 0.5 })] },
    { id: 'cp_fine_print', name: 'Fine Print', charge: 0, target: 'self', fx: 'buff',
      desc: 'Extend one beneficial and one harmful effect by a turn.',
      effects: [ef('onSkillUse', 'extendStatus', { status: 'hexed', turns: 1, selfHarm: true })] },
    { id: 'cp_appeal_denied', name: 'Appeal Denied', charge: 1, cooldown: 1, power: 110, stat: 'int', fx: 'arcane',
      desc: 'Stronger against marked, judged, or hexed targets.',
      effects: [ef('onHit', 'modDamage', { vsStatus: 'hexed', mult: 1.2 })] },
    { id: 'cp_hex_bargain', name: 'Hex Bargain', charge: 1, cooldown: 2, target: 'one', power: 70, stat: 'int', fx: 'arcane',
      desc: 'Spend HP to deepen a hex and refund Pact.',
      effects: [ef('onSkillUse', 'applyStatus', { status: 'hexed', turns: 3 }), ef('onSkillUse', 'grantResource', { amount: 6 })] },
    { id: 'cp_invoice_comes_due', name: 'Invoice Comes Due', charge: 2, cooldown: 2, power: 125, stat: 'int', fx: 'arcane',
      desc: 'Collect stored hex debt as damage.',
      effects: [ef('onHit', 'modDamage', { vsStatus: 'hexed', mult: 1.25 })] },
    { id: 'cp_seventh_signature', name: 'Seventh Signature', charge: 3, cooldown: 3, target: 'self', fx: 'buff',
      desc: 'Once per combat, contest a lethal or punitive effect at a visible price.',
      effects: [ef('onSkillUse', 'contestLethal', { amount: 10 })] },
  ]),
  ...kit('viking', [
    { id: 'cp_shield_wall_step', name: 'Shield-Wall Step', charge: 0, target: 'self', fx: 'buff',
      desc: 'Free defensive brace that stores raid momentum.',
      guard: true,
      effects: [
        ef('onSkillUse', 'armNextIncoming', { mult: 0.85 }),
        ef('onSkillUse', 'armNextHit', { add: 3 }),
      ] },
    { id: 'cp_raid_mark', name: 'Raid Mark', charge: 0, power: 90, stat: 'str', fx: 'slash',
      desc: 'Mark a target as the raid\'s due.',
      effects: [ef('onHit', 'markTarget')] },
    { id: 'cp_fury_hook', name: 'Fury Hook', charge: 1, cooldown: 1, power: 110, stat: 'str', fx: 'slash',
      desc: 'Pull attention and convert recent HP loss into damage.',
      effects: [ef('onHit', 'modDamage', { add: 4 })] },
    { id: 'cp_blood_price', name: 'Blood Price', charge: 1, cooldown: 2, target: 'self', fx: 'buff', selfHpCost: 0.06,
      desc: 'Pay HP for a combat-long fury bonus.',
      effects: [ef('onSkillUse', 'setOath', { oath: 'conquer' })] },
    { id: 'cp_longship_break', name: 'Longship Break', charge: 2, cooldown: 2, power: 120, stat: 'str', fx: 'slash',
      desc: 'Heavy strike that ignores part of a shield.',
      effects: [ef('onHit', 'modDamage', { vsShielded: 1.25 })] },
    { id: 'cp_valhalla_echo', name: 'Valhalla Echo', charge: 3, cooldown: 3, power: 150, stat: 'str', fx: 'slash',
      desc: 'Finisher that refunds a sliver of Fury on a kill.',
      effects: [ef('onKill', 'grantResource', { amount: 10, once: 'combat' })] },
  ]),
  /* bloodline arts */
  ...kit('universal', [
    { id: 'cp_art_borrowed_mastery', name: 'Borrowed Mastery', class: 'universal', bloodline: 'human', charge: 1, cooldown: 2, target: 'self', fx: 'buff',
      desc: 'Human art · temporarily adopt a weakened technique category from another class.',
      capability: 'bloodline_art',
      effects: [ef('onSkillUse', 'borrowTechnique')] },
    { id: 'cp_art_refuse_classification', name: 'Refuse Classification', class: 'universal', bloodline: 'human', charge: 0, target: 'self', fx: 'buff',
      desc: 'Human art · flexible benefit when an event or enemy attempts to categorize the character.',
      capability: 'bloodline_art',
      effects: [
        ef('onSkillUse', 'armNextIncoming', { mult: 0.9 }),
        ef('onSkillUse', 'armNextHit', { add: 2 }),
      ] },
    { id: 'cp_art_long_memory', name: 'Long Memory', class: 'universal', bloodline: 'elf', charge: 0, target: 'self', fx: 'buff',
      desc: 'Elf art · improve against an enemy family previously encountered in the run.',
      capability: 'bloodline_art',
      effects: [ef('onSkillUse', 'storeMemory', { key: 'memoryFamily', scope: 'run' })] },
    { id: 'cp_art_root_communion', name: 'Root Communion', class: 'universal', bloodline: 'elf', charge: 1, cooldown: 2, target: 'self', fx: 'buff',
      desc: 'Elf art · exchange immediate power for a stronger delayed effect.',
      capability: 'bloodline_art',
      effects: [ef('onSkillUse', 'delayEffect', { delayTurns: 1, add: 8 })] },
    { id: 'cp_art_scar_oath', name: 'Scar Oath', class: 'universal', bloodline: 'orc', charge: 0, target: 'self', fx: 'buff',
      desc: 'Orc art · after a major wound, swear to protect, avenge, or conquer.',
      capability: 'bloodline_art',
      effects: [ef('onSkillUse', 'setOath', { oath: 'avenge' })] },
    { id: 'cp_art_clan_before_self', name: 'Clan Before Self', class: 'universal', bloodline: 'orc', charge: 1, cooldown: 2, target: 'self', fx: 'buff',
      desc: 'Orc art · redirect a portion of ally damage and gain a retaliation benefit.',
      capability: 'bloodline_art',
      effects: [ef('onSkillUse', 'redirectDamage', { pct: 0.3, mutex: 'damage_redirect' })] },
    { id: 'cp_art_field_reforge', name: 'Field Reforge', class: 'universal', bloodline: 'dwarf', charge: 1, cooldown: 2, target: 'self', fx: 'buff',
      desc: 'Dwarf art · temporarily alter one ordinary gear property (normalized).',
      capability: 'bloodline_art',
      effects: [ef('onSkillUse', 'armNextHit', { add: 4, mult: 1.08 })] },
    { id: 'cp_art_structural_weakness', name: 'Structural Weakness', class: 'universal', bloodline: 'dwarf', charge: 0, power: 80, stat: 'str', fx: 'blunt',
      desc: 'Dwarf art · expose armor, gates, constructs, and defensive enemies.',
      capability: 'bloodline_art',
      effects: [ef('onHit', 'modDamage', { vsShielded: 1.2, vsFamily: 'golem', mult: 1.15 })] },
    { id: 'cp_art_improbably_prepared', name: 'Improbably Prepared', class: 'universal', bloodline: 'halfling', charge: 0, target: 'self', fx: 'buff',
      desc: 'Halfling art · reveal one context-specific minor consumable (allowlisted).',
      capability: 'bloodline_art',
      effects: [ef('onSkillUse', 'heal', { amount: 10 })] },
    { id: 'cp_art_one_more_meal', name: 'One More Meal', class: 'universal', bloodline: 'halfling', charge: 1, cooldown: 2, target: 'self', fx: 'heal', healPct: 0.1,
      desc: 'Halfling art · convert food or rest benefits into emergency combat recovery.',
      capability: 'bloodline_art',
      effects: [ef('onSkillUse', 'heal', { pct: 0.08 })] },
    { id: 'cp_art_fine_print_clause', name: 'Fine-Print Clause', class: 'universal', bloodline: 'tiefling', charge: 0, target: 'self', fx: 'buff',
      desc: 'Tiefling art · extend both a beneficial and harmful effect.',
      capability: 'bloodline_art',
      effects: [ef('onSkillUse', 'extendStatus', { status: 'burn', turns: 1, selfHarm: true })] },
    { id: 'cp_art_appeal_from_damnation', name: 'Appeal from Damnation', class: 'universal', bloodline: 'tiefling', charge: 2, cooldown: 3, target: 'self', fx: 'buff',
      desc: 'Tiefling art · once per combat, contest a lethal or punitive effect at a visible price.',
      capability: 'bloodline_art',
      effects: [ef('onSkillUse', 'contestLethal', { amount: 8 })] },
    { id: 'cp_art_pack_scent', name: 'Pack Scent', class: 'universal', bloodline: 'beastfolk', charge: 0, target: 'one', power: 50, stat: 'dex', fx: 'pierce',
      desc: 'Beastfolk art · benefits when pursuing the same target as an ally.',
      capability: 'bloodline_art',
      effects: [ef('onHit', 'markTarget')] },
    { id: 'cp_art_instinct_before_intent', name: 'Instinct Before Intent', class: 'universal', bloodline: 'beastfolk', charge: 1, cooldown: 2, target: 'self', fx: 'buff',
      desc: 'Beastfolk art · prepare a response before an enemy intent fully resolves.',
      capability: 'bloodline_art',
      effects: [ef('onSkillUse', 'revealIntent', { value: 'shape' })] },
    { id: 'cp_art_ancestral_breath', name: 'Ancestral Breath', class: 'universal', bloodline: 'dragonkin', charge: 2, cooldown: 2, power: 110, stat: 'str', fx: 'fire',
      desc: 'Dragonkin art · breath effect changes according to stored elemental damage.',
      capability: 'bloodline_art',
      effects: [ef('onHit', 'statusChance', { status: 'burn', chance: 0.5 })] },
    { id: 'cp_art_hoard_authority', name: 'Hoard Authority', class: 'universal', bloodline: 'dragonkin', charge: 1, cooldown: 2, target: 'self', fx: 'buff',
      desc: 'Dragonkin art · held gold provides power, but spending suppresses it for one combat.',
      capability: 'bloodline_art',
      effects: [ef('onSkillUse', 'spendGoldPower', { gold: 8, mult: 1.18 })] },
  ]),
].map(sk => [sk.id, sk]));
