import { wpn, ef } from './helpers.js';

const guardNext = [
  ef('onGuard', 'setFlag', { key: 'guarded', scope: 'turn' }),
  ef('onHit', 'modDamage', { mult: 1.12, when: { flag: 'guarded' }, once: 'turn' }),
];

export const PACK_WEAPONS = [
  /* ---- I. Foundation ---- */
  wpn({ id: 'cp_gate_iron_sword', name: 'Gate-Iron Sword', wtype: 'sword', rarity: 'common', tier: 1, atk: 3, packOrdinary: true, minFloor: 1, maxFloor: 20,
    desc: 'Sword · +3 dmg. Guarding before a strike slightly strengthens the next hit.', effects: guardNext }),
  wpn({ id: 'cp_surveyors_spear', name: "Surveyor's Spear", wtype: 'spear', rarity: 'common', tier: 1, atk: 3, packOrdinary: true, minFloor: 1, maxFloor: 20,
    desc: 'Spear · +3 dmg. Extra bite against enemies winding a charged special.',
    effects: [ef('onHit', 'modDamage', { vsCharging: 1.18 })] }),
  wpn({ id: 'cp_root_cutter_axe', name: 'Root-Cutter Axe', wtype: 'axe', rarity: 'common', tier: 1, atk: 3, packOrdinary: true, minFloor: 1, maxFloor: 20,
    desc: 'Axe · +3 dmg. Better against shields, roots, and defensive statuses.',
    effects: [ef('onHit', 'modDamage', { vsShielded: 1.16, vsStatus: 'frail', mult: 1.08 })] }),
  wpn({ id: 'cp_kiln_hammer', name: 'Kiln Hammer', wtype: 'mace', rarity: 'common', tier: 1, atk: 3,
    desc: 'Mace · +3 dmg. Slow heat: hitting an already-armored foe may add burn.',
    effects: [ef('onHit', 'statusChance', { status: 'burn', chance: 0.2, when: { status: 'frail' } })] }),
  wpn({ id: 'cp_frost_miners_pick', name: "Frost Miner's Pick", wtype: 'axe', rarity: 'common', tier: 1, atk: 3,
    desc: 'Axe · +3 dmg. Extra damage to frozen, stunned, or brittle targets.',
    effects: [ef('onHit', 'modDamage', { vsStatus: 'frozen', mult: 1.2 })] }),
  wpn({ id: 'cp_bog_hook', name: 'Bog Hook', wtype: 'axe', rarity: 'common', tier: 1, atk: 2,
    desc: 'Axe · +2 dmg. Pulls attention toward the wielder.',
    effects: [ef('onHit', 'applyStatus', { status: 'marked', turns: 1 })] }),
  wpn({ id: 'cp_ashwood_bow', name: 'Ashwood Bow', wtype: 'bow', rarity: 'common', tier: 1, atk: 3, packOrdinary: true, minFloor: 1, maxFloor: 20,
    desc: 'Bow · +3 dmg. First attack against each enemy is slightly stronger.',
    effects: [ef('onHit', 'modDamage', { mult: 1.12, firstHit: true })] }),
  wpn({ id: 'cp_ruin_repeater', name: 'Ruin Repeater', wtype: 'bow', rarity: 'uncommon', tier: 2, atk: 4,
    desc: 'Bow · +4 dmg. Rewards alternating targets.',
    effects: [ef('onHit', 'modDamage', { mult: 1.14, when: { differentFromPrior: true } })] }),
  wpn({ id: 'cp_court_rapier', name: 'Court Rapier', wtype: 'sword', rarity: 'uncommon', tier: 2, atk: 4, dex: 1,
    desc: 'Sword · +4 dmg, +1 DEX. Precision after avoiding damage.',
    effects: [ef('onMiss', 'setFlag', { key: 'evaded', scope: 'turn' }), ef('onHit', 'modDamage', { mult: 1.12, when: { flag: 'evaded' } })] }),
  wpn({ id: 'cp_pilgrims_staff', name: "Pilgrim's Staff", wtype: 'staff', rarity: 'common', tier: 1, atk: 2, wis: 2, packOrdinary: true, minFloor: 1, maxFloor: 20,
    desc: 'Staff · +2 dmg, +2 WIS. Improves defensive and healing techniques.',
    effects: [ef('onHeal', 'heal', { pct: 0.02 })] }),
  wpn({ id: 'cp_grave_mace', name: 'Grave Mace', wtype: 'mace', rarity: 'uncommon', tier: 2, atk: 4,
    desc: 'Mace · +4 dmg. Better against undead, summons, and death-related shields.',
    effects: [ef('onHit', 'modDamage', { vsSummon: 1.2, vsFamily: 'skeleton', mult: 1.12 })] }),
  wpn({ id: 'cp_chain_whip', name: 'Chain Whip', wtype: 'sword', rarity: 'uncommon', tier: 2, atk: 3,
    desc: 'Sword · +3 dmg. Can spread a minor status to the current target.',
    effects: [ef('onHit', 'statusChance', { status: 'weaken', chance: 0.18 })] }),
  wpn({ id: 'cp_crescent_glaive', name: 'Crescent Glaive', wtype: 'spear', rarity: 'uncommon', tier: 2, atk: 4,
    desc: 'Spear · +4 dmg. Alternates a stronger single-target bite with a lighter follow-up.',
    effects: [ef('onHit', 'addCounter', { key: 'glaiveSwing', scope: 'combat' }),
      ef('onHit', 'modDamage', { mult: 1.16, when: { flag: 'glaiveSwing' } })] }),
  wpn({ id: 'cp_travelers_sling', name: "Traveler's Sling", wtype: 'bow', rarity: 'common', tier: 1, atk: 2, lk: 1,
    desc: 'Sling · +2 dmg, +1 LK. Improves combat-item potency.',
    effects: [ef('onConsumable', 'heal', { amount: 4 })] }),
  wpn({ id: 'cp_gate_nail_javelins', name: 'Gate Nail Javelins', wtype: 'spear', rarity: 'uncommon', tier: 2, atk: 3,
    desc: 'Spear · +3 dmg. Interferes with enemy charge.',
    effects: [ef('onHit', 'reduceCharge', { amount: 1, once: 'turn' })] }),
  wpn({ id: 'cp_iron_knuckle_wraps', name: 'Iron Knuckle Wraps', wtype: 'fist', rarity: 'common', tier: 1, atk: 3, packOrdinary: true, minFloor: 1, maxFloor: 20,
    desc: 'Fist · +3 dmg. Repeated basics gradually strengthen until another action is used.',
    effects: [ef('onHit', 'addCounter', { key: 'wrapCombo', scope: 'combat', when: { differentFromPrior: false } }),
      ef('onHit', 'modDamage', { add: 1 })] }),
  wpn({ id: 'cp_scavenger_war_scythe', name: "Scavenger's War Scythe", wtype: 'axe', rarity: 'uncommon', tier: 2, atk: 4,
    desc: 'Axe · +4 dmg. Small benefit when finishing weakened enemies.',
    effects: [ef('onKill', 'grantCharge', { amount: 1, once: 'combat' })] }),
  wpn({ id: 'cp_spellknife', name: 'Spellknife', wtype: 'dagger', rarity: 'uncommon', tier: 2, atk: 3, int: 1, packOrdinary: true, minFloor: 6, maxFloor: 30,
    desc: 'Dagger · +3 dmg, +1 INT. Converts a sliver of magical potency into the hit.',
    effects: [ef('onHit', 'modDamage', { add: 1 })] }),
  wpn({ id: 'cp_monsterbone_club', name: 'Monsterbone Club', wtype: 'mace', rarity: 'uncommon', tier: 2, atk: 4,
    desc: 'Mace · +4 dmg. Randomly applies one minor monster-derived rider.',
    effects: [ef('onHit', 'statusChance', { status: 'poison', chance: 0.12 })] }),
  wpn({ id: 'cp_twin_hatchets', name: 'Twin Hatchets', wtype: 'axe', rarity: 'uncommon', tier: 2, atk: 3,
    desc: 'Axe · +3 dmg. Second consecutive basic becomes a two-hit attack (bounded).',
    effects: [ef('onHit', 'echoAction', { mult: 0.45, when: { differentFromPrior: false }, once: 'turn', capability: 'echo_copy' })] }),
  wpn({ id: 'cp_towerbreaker_maul', name: 'Towerbreaker Maul', wtype: 'mace', rarity: 'rare', tier: 3, atk: 6, str: 1,
    desc: 'Mace · +6 dmg, +1 STR. Large bonus against shields; poorer vs evasive foes.',
    effects: [ef('onHit', 'modDamage', { vsShielded: 1.22 })] }),
  wpn({ id: 'cp_refugee_shortbow', name: 'Refugee Shortbow', wtype: 'bow', rarity: 'uncommon', tier: 2, atk: 3,
    desc: 'Bow · +3 dmg. Small Fame after protecting a low-health ally.',
    effects: [ef('onDamageTaken', 'gainFame', { amount: 1, when: { hpBelow: 0.35 }, once: 'combat' })] }),
  wpn({ id: 'cp_gatekeeper_bucklerblade', name: 'Gatekeeper Bucklerblade', wtype: 'sword', rarity: 'uncommon', tier: 2, atk: 3, def: 1,
    desc: 'Sword · +3 dmg, +1 DEF. Improves counterattacks after Guard.', effects: guardNext }),
  wpn({ id: 'cp_funeral_bell_flail', name: 'Funeral Bell Flail', wtype: 'mace', rarity: 'rare', tier: 3, atk: 5,
    desc: 'Mace · +5 dmg. Defeating an enemy slightly heals the lowest-health ally once per combat.',
    effects: [ef('onKill', 'heal', { pct: 0.06, once: 'combat', lowestAlly: true })] }),

  /* ---- II. Class signature ---- */
  /* Warrior */
  wpn({ id: 'cp_gatebreaker_greatsword', name: 'Gatebreaker Greatsword', wtype: 'sword', rarity: 'rare', tier: 3, atk: 7, str: 2, classBound: 'warrior', acquisition: 'class',
    desc: 'Warrior · charged attacks partially ignore shields; breaking a shield opens a retaliation window.',
    effects: [ef('onHit', 'modDamage', { vsShielded: 1.2, vsCharging: 1.1 })] }),
  wpn({ id: 'cp_bastion_nail', name: 'Bastion Nail', wtype: 'sword', rarity: 'rare', tier: 3, atk: 6, def: 2, classBound: 'warrior', acquisition: 'class',
    desc: 'Warrior · Guarding plants the nail: +defense this turn.',
    effects: [ef('onGuard', 'setFlag', { key: 'planted', scope: 'turn' }), ef('beforeDamageTaken', 'modIncoming', { mult: 0.88, when: { flag: 'planted' } })] }),
  wpn({ id: 'cp_seven_oath_halberd', name: 'Seven-Oath Halberd', wtype: 'spear', rarity: 'epic', tier: 4, atk: 8, classBound: 'warrior', acquisition: 'class',
    desc: 'Warrior · choose an oath at combat start (protect / endure / avenge).',
    effects: [ef('onCombatStart', 'setOath', { oath: 'endure' }), ef('onHit', 'modDamage', { mult: 1.08 })] }),
  wpn({ id: 'cp_bell_bearers_maul', name: "Bell-Bearer's Maul", wtype: 'mace', rarity: 'epic', tier: 4, atk: 8, classBound: 'warrior', acquisition: 'class',
    desc: 'Warrior · damage taken stores resonance; a charged technique releases it without extra Battle Charge.',
    effects: [ef('onDamageTaken', 'addCounter', { key: 'resonance', scope: 'combat' }),
      ef('onHit', 'modDamage', { add: 2, when: { charged: true } })] }),
  wpn({ id: 'cp_coward_kings_shieldblade', name: "Coward King's Shieldblade", wtype: 'sword', rarity: 'rare', tier: 3, atk: 5, def: 2, classBound: 'warrior', acquisition: 'class',
    desc: 'Warrior · very strong while Guarding; weaker when striking someone else\'s target.',
    effects: [ef('onGuard', 'setFlag', { key: 'cowardGuard', scope: 'turn' }), ef('onHit', 'modDamage', { mult: 1.2, when: { flag: 'cowardGuard' } })] }),
  wpn({ id: 'cp_world_shutting_door', name: 'World-Shutting Door', wtype: 'mace', rarity: 'legendary', tier: 5, atk: 12, def: 3, classBound: 'warrior', acquisition: 'class', unique: true,
    desc: 'Legendary tower shield-weapon. Once per combat, intercept an AOE into personal damage.',
    effects: [ef('beforeDamageTaken', 'interceptAoe', { pct: 0.7, once: 'combat', mutex: 'damage_redirect' })] }),

  /* Mage */
  wpn({ id: 'cp_margin_script_staff', name: 'Margin-Script Staff', wtype: 'staff', rarity: 'rare', tier: 3, atk: 4, int: 3, classBound: 'mage', acquisition: 'class',
    desc: 'Mage · the first spell is annotated; a different spell modifies its next cast.',
    effects: [ef('onSkillUse', 'storeMemory', { key: 'annotated', scope: 'combat' }),
      ef('onHit', 'modDamage', { mult: 1.1, when: { differentFromPrior: true } })] }),
  wpn({ id: 'cp_starfall_grimoire', name: 'Starfall Grimoire', wtype: 'staff', rarity: 'epic', tier: 4, atk: 5, int: 4, classBound: 'mage', acquisition: 'class',
    desc: 'Mage · builds fragments through varied actions, then spends them on a meteor-like strike.',
    effects: [ef('onSkillUse', 'addCounter', { key: 'fragments', scope: 'combat' }),
      ef('onHit', 'modDamage', { add: 3 })] }),
  wpn({ id: 'cp_paradox_wand', name: 'Paradox Wand', wtype: 'staff', rarity: 'rare', tier: 3, atk: 4, int: 3, classBound: 'mage', acquisition: 'class',
    desc: 'Mage · repeats the weakest prior spell at reduced strength (copy-depth 1).',
    effects: [ef('onTurnEnd', 'echoAction', { mult: 0.4, once: 'turn', capability: 'echo_copy' })] }),
  wpn({ id: 'cp_gate_cartographers_compass', name: "Gate Cartographer's Compass", wtype: 'staff', rarity: 'rare', tier: 3, atk: 3, int: 3, classBound: 'mage', acquisition: 'class',
    desc: 'Mage · spells against a charging enemy reveal or weaken its next intent.',
    effects: [ef('onHit', 'weakenIntent', { mult: 0.9, when: { charged: true } }), ef('onHit', 'revealIntent', { value: 'shape', once: 'combat' })] }),
  wpn({ id: 'cp_frost_oracles_rod', name: "Frost Oracle's Rod", wtype: 'staff', rarity: 'epic', tier: 4, atk: 5, int: 4, freeze: 0.12, classBound: 'mage', acquisition: 'class',
    desc: 'Mage · one spell per combat can be prepared and released later at improved potency.',
    effects: [ef('onSkillUse', 'setFlag', { key: 'prepared', scope: 'combat' }),
      ef('onHit', 'modDamage', { mult: 1.18, when: { flag: 'prepared' }, once: 'combat' })] }),
  wpn({ id: 'cp_administrator_error_scepter', name: 'Administrator Error Scepter', wtype: 'staff', rarity: 'legendary', tier: 5, atk: 10, int: 5, classBound: 'mage', acquisition: 'class', unique: true,
    desc: 'Legendary · transform one resisted status into another once per combat, then weaken the next intent.',
    effects: [
      ef('onHit', 'convertStatus', { status: 'weaken', statusTo: 'frail', once: 'combat' }),
      ef('onHit', 'weakenIntent', { mult: 0.85, once: 'combat' }),
    ] }),

  /* Ranger (archer) */
  wpn({ id: 'cp_three_trails_longbow', name: 'Three-Trails Longbow', wtype: 'bow', rarity: 'rare', tier: 3, atk: 6, dex: 2, classBound: 'archer', acquisition: 'class',
    desc: 'Ranger · choose Hunt, Rescue, or Escape at combat start.',
    effects: [ef('onCombatStart', 'chooseStance', { stance: 'hunt' }),
      ef('onHit', 'modDamage', { mult: 1.16, when: { stance: 'hunt' } }),
      ef('onHit', 'heal', { amount: 3, when: { stance: 'rescue' }, once: 'turn' }),
      ef('beforeDamageTaken', 'modIncoming', { mult: 0.9, when: { stance: 'escape' } })] }),
  wpn({ id: 'cp_gate_beast_spinebow', name: 'Gate-Beast Spinebow', wtype: 'bow', rarity: 'epic', tier: 4, atk: 7, dex: 3, classBound: 'archer', acquisition: 'class',
    desc: 'Ranger · marked targets stay easier to track through summons or transformations.',
    effects: [ef('onHit', 'markTarget', { turns: 3 }), ef('onHit', 'modDamage', { when: { targetMarked: true }, mult: 1.12 })] }),
  wpn({ id: 'cp_crowned_deer_antlerbow', name: 'Crowned Deer Antlerbow', wtype: 'bow', rarity: 'rare', tier: 3, atk: 6, classBound: 'archer', acquisition: 'class',
    desc: 'Ranger · repeating a target increases precision; switching grants evasion.',
    effects: [ef('onHit', 'modDamage', { mult: 1.12, when: { sameTarget: true } })] }),
  wpn({ id: 'cp_ashen_rivals_recurve', name: "Ashen Rival's Recurve", wtype: 'bow', rarity: 'epic', tier: 4, atk: 7, classBound: 'archer', acquisition: 'class',
    desc: 'Ranger · stronger when another party member attacks the marked target.',
    effects: [ef('onHit', 'modDamage', { mult: 1.1 })] }),
  wpn({ id: 'cp_avalanche_repeater', name: 'Avalanche Repeater', wtype: 'bow', rarity: 'epic', tier: 4, atk: 6, classBound: 'archer', acquisition: 'class',
    desc: 'Ranger · every third distinct target hit triggers a controlled extra shot (depth 1).',
    effects: [ef('onHit', 'addCounter', { key: 'distinctHits', scope: 'combat' }),
      ef('onHit', 'echoAction', { mult: 0.4, once: 'turn', capability: 'echo_copy' })] }),
  wpn({ id: 'cp_world_scent_javelin', name: 'World-Scent Javelin', wtype: 'spear', rarity: 'legendary', tier: 5, atk: 11, dex: 4, classBound: 'archer', acquisition: 'class', unique: true,
    desc: 'Legendary spear · mark an enemy across phases (normalized family id only).',
    effects: [
      ef('onHit', 'markTarget'),
      ef('onHit', 'modDamage', { when: { targetMarked: true }, mult: 1.18 }),
      ef('onCombatStart', 'storeMemory', { key: 'preyFamily', scope: 'run' }),
    ] }),

  /* Rogue */
  wpn({ id: 'cp_receipt_knife', name: 'Receipt Knife', wtype: 'dagger', rarity: 'rare', tier: 3, atk: 4, crit: 6, classBound: 'rogue', acquisition: 'class',
    desc: 'Rogue · steals a small tactical fee from shielded or buffed enemies.',
    effects: [ef('onHit', 'modDamage', { vsShielded: 1.14 }), ef('onHit', 'reduceCharge', { amount: 1, once: 'turn' })] }),
  wpn({ id: 'cp_echo_twin_daggers', name: 'Echo Twin Daggers', wtype: 'dagger', rarity: 'epic', tier: 4, atk: 5, classBound: 'rogue', acquisition: 'class',
    desc: 'Rogue · off-hand repeats last turn\'s attack at reduced strength if a different technique is used.',
    effects: [ef('onHit', 'echoAction', { mult: 0.45, when: { differentFromPrior: true }, once: 'turn', capability: 'echo_copy' })] }),
  wpn({ id: 'cp_invisible_toll_garrote', name: 'Invisible-Toll Garrote', wtype: 'dagger', rarity: 'rare', tier: 3, atk: 4, classBound: 'rogue', acquisition: 'class',
    desc: 'Rogue · strong against enemies that gained charge since your last turn.',
    effects: [ef('onHit', 'modDamage', { vsCharging: 1.2 })] }),
  wpn({ id: 'cp_last_door_keyblade', name: 'Last-Door Keyblade', wtype: 'dagger', rarity: 'epic', tier: 4, atk: 5, classBound: 'rogue', acquisition: 'class',
    desc: 'Rogue · three different debuffs unlock a finisher bonus.',
    effects: [ef('onHit', 'modDamage', { vsStatus: 'weaken', mult: 1.15 })] }),
  wpn({ id: 'cp_counterfeit_halo_chakram', name: 'Counterfeit Halo Chakram', wtype: 'dagger', rarity: 'rare', tier: 3, atk: 4, classBound: 'rogue', acquisition: 'class',
    desc: 'Rogue · Fame when used honorably; bonus damage when that Fame is spent dishonestly.',
    effects: [ef('onKill', 'gainFame', { amount: 1, once: 'combat' }), ef('onHit', 'spendFamePower', { fame: 1, mult: 1.12, once: 'turn' })] }),
  wpn({ id: 'cp_black_ledger_stiletto', name: 'Black-Ledger Stiletto', wtype: 'dagger', rarity: 'legendary', tier: 5, atk: 8, crit: 14, classBound: 'rogue', acquisition: 'class', unique: true,
    desc: 'Legendary · records damage owed and collects when a target tries to heal or shield.',
    effects: [ef('onHit', 'addCounter', { key: 'owed', scope: 'combat' }), ef('onHit', 'modDamage', { add: 4 })] }),

  /* Priest */
  wpn({ id: 'cp_nameless_reliquary', name: 'Nameless Reliquary', wtype: 'mace', rarity: 'rare', tier: 3, atk: 4, wis: 3, classBound: 'priest', acquisition: 'class',
    desc: 'Priest · healing records a name; later judgment protects recorded allies.',
    effects: [ef('onHeal', 'recordName'), ef('onHit', 'modDamage', { mult: 1.08 })] }),
  wpn({ id: 'cp_heretics_bell', name: "Heretic's Bell", wtype: 'mace', rarity: 'epic', tier: 4, atk: 5, wis: 3, classBound: 'priest', acquisition: 'class',
    desc: 'Priest · offensive miracles stronger after healing an enemy or sparing the vulnerable.',
    effects: [ef('onHit', 'modDamage', { mult: 1.12 }), ef('onHit', 'leaveAtOne', { once: 'combat' })] }),
  wpn({ id: 'cp_mercy_thorn_mace', name: 'Mercy Thorn Mace', wtype: 'mace', rarity: 'rare', tier: 3, atk: 5, classBound: 'priest', acquisition: 'class',
    desc: 'Priest · can leave an enemy at 1 HP, creating a spare / execute choice.',
    effects: [ef('onHit', 'leaveAtOne', { once: 'combat' })] }),
  wpn({ id: 'cp_saints_empty_icon', name: "Saint's Empty Icon", wtype: 'staff', rarity: 'epic', tier: 4, atk: 4, wis: 4, classBound: 'priest', acquisition: 'class',
    desc: 'Priest · different blessing depending on who receives the first heal.',
    effects: [ef('onHeal', 'setFlag', { key: 'firstHeal', scope: 'combat' }), ef('onHeal', 'heal', { amount: 4, once: 'combat' })] }),
  wpn({ id: 'cp_censer_funeral_gate', name: 'Censer of the Funeral Gate', wtype: 'mace', rarity: 'rare', tier: 3, atk: 4, wis: 3, classBound: 'priest', acquisition: 'class',
    desc: 'Priest · overhealing becomes a temporary ward.',
    effects: [ef('onHeal', 'overhealWard')] }),
  wpn({ id: 'cp_staff_seven_forgotten_names', name: 'Staff of Seven Forgotten Names', wtype: 'staff', rarity: 'legendary', tier: 5, atk: 9, wis: 5, classBound: 'priest', acquisition: 'class', unique: true,
    desc: 'Legendary · collects one name from each major biome and awakens at the throne.',
    effects: [ef('onBiomeEnter', 'addCounter', { key: 'names', scope: 'run' }), ef('onHit', 'modDamage', { add: 2 })] }),

  /* Monk */
  wpn({ id: 'cp_root_memory_wraps', name: 'Root-Memory Wraps', wtype: 'fist', rarity: 'rare', tier: 3, atk: 5, dex: 2, classBound: 'monk', acquisition: 'class',
    desc: 'Monk · repeating an action is weaker; alternating builds Flow.',
    effects: [ef('onHit', 'modDamage', { mult: 1.14, when: { differentFromPrior: true } })] }),
  wpn({ id: 'cp_empty_hand_seal', name: 'Empty-Hand Seal', wtype: 'fist', rarity: 'epic', tier: 4, atk: 6, classBound: 'monk', acquisition: 'class',
    desc: 'Monk · stronger for every unequipped weapon slot or deliberately unused relic (bounded).',
    effects: [ef('onHit', 'modDamage', { add: 2, emptySlots: true })],
    playable: 'adapted', adaptation: 'Counts empty weapon/relic slots as a small additive bonus; does not disable other gear effects.' }),
  wpn({ id: 'cp_glacier_heart_beads', name: 'Glacier-Heart Beads', wtype: 'fist', rarity: 'rare', tier: 3, atk: 4, classBound: 'monk', acquisition: 'class',
    desc: 'Monk · damage taken while calm is stored and released through the next counter.',
    effects: [ef('onDamageTaken', 'addCounter', { key: 'stored', scope: 'combat' }), ef('onHit', 'modDamage', { add: 2 })] }),
  wpn({ id: 'cp_rhythm_breaker_tonfa', name: 'Rhythm-Breaker Tonfa', wtype: 'fist', rarity: 'epic', tier: 4, atk: 6, classBound: 'monk', acquisition: 'class',
    desc: 'Monk · interrupting an enemy intent changes the next technique.',
    effects: [ef('onHit', 'weakenIntent', { mult: 0.9, when: { charged: true } })] }),
  wpn({ id: 'cp_gate_carrying_bracers', name: 'Gate-Carrying Bracers', wtype: 'fist', rarity: 'rare', tier: 3, atk: 5, classBound: 'monk', acquisition: 'class',
    desc: 'Monk · protecting allies adds Burden that converts into damage or healing.',
    effects: [ef('onDamageTaken', 'addCounter', { key: 'burden', scope: 'combat' }), ef('onHit', 'modDamage', { add: 1 })] }),
  wpn({ id: 'cp_staff_no_possession', name: 'Staff of No Possession', wtype: 'staff', rarity: 'legendary', tier: 5, atk: 10, dex: 3, classBound: 'monk', acquisition: 'class', unique: true,
    desc: 'Legendary · temporarily disables one relic (mutex) to awaken a powerful stance.',
    effects: [ef('onCombatStart', 'chooseStance', { stance: 'empty' }), ef('onHit', 'modDamage', { mult: 1.22 })],
    playable: 'adapted', adaptation: 'Does not strip relics mid-combat; mutexes one extra-relic family and grants Empty stance instead.' }),

  /* Bard */
  wpn({ id: 'cp_applause_eater_lute', name: 'Applause-Eater Lute', wtype: 'instrument', rarity: 'rare', tier: 3, atk: 4, lk: 3, classBound: 'bard', acquisition: 'class',
    desc: 'Bard · spend Fame to strengthen songs; finishing without spending feeds the lute.',
    effects: [ef('onHit', 'spendFamePower', { fame: 1, mult: 1.12, once: 'turn' })] }),
  wpn({ id: 'cp_rivals_encore_violin', name: "Rival's Encore Violin", wtype: 'instrument', rarity: 'epic', tier: 4, atk: 5, classBound: 'bard', acquisition: 'class',
    desc: 'Bard · copies the last support technique used by an ally at reduced power (depth 1).',
    effects: [ef('onSkillUse', 'copySupport', { mult: 0.55, capability: 'echo_copy' })] }),
  wpn({ id: 'cp_gate_queue_war_drum', name: 'Gate-Queue War Drum', wtype: 'instrument', rarity: 'epic', tier: 4, atk: 5, classBound: 'bard', acquisition: 'class',
    desc: 'Bard · small initiative bump for consecutive ally actions (no extra turns).',
    effects: [ef('onCombatStart', 'grantCharge', { amount: 1 })],
    playable: 'adapted', adaptation: 'Does not reorder the live turn table; grants Battle Charge as initiative instead of extra turns.' }),
  wpn({ id: 'cp_false_hero_hymnal', name: 'False Hero Hymnal', wtype: 'instrument', rarity: 'rare', tier: 3, atk: 4, classBound: 'bard', acquisition: 'class',
    desc: 'Bard · songs grow stronger for low-Fame or unrecognized allies.',
    effects: [ef('onHit', 'modDamage', { mult: 1.12, when: { fameBelow: 8 } })] }),
  wpn({ id: 'cp_drowned_court_viola', name: 'Drowned Court Viola', wtype: 'instrument', rarity: 'epic', tier: 4, atk: 5, classBound: 'bard', acquisition: 'class',
    desc: 'Bard · lingering refrain when enemies change phase.',
    effects: [ef('onPhaseChange', 'statusChance', { status: 'weaken', chance: 1 })] }),
  wpn({ id: 'cp_bell_final_chorus', name: 'Bell of the Final Chorus', wtype: 'instrument', rarity: 'legendary', tier: 5, atk: 9, lk: 4, classBound: 'bard', acquisition: 'class', unique: true,
    desc: 'Legendary · combines currently active song flags into one crescendo once per combat.',
    effects: [ef('onHit', 'modDamage', { mult: 1.3, once: 'combat' })] }),

  /* Necromancer */
  wpn({ id: 'cp_seventh_hero_phylactery', name: 'Seventh-Hero Phylactery', wtype: 'staff', rarity: 'epic', tier: 4, atk: 5, int: 3, classBound: 'necromancer', acquisition: 'class',
    desc: 'Necromancer · stores the first defeated summon or minor archetype (safe allowlist).',
    effects: [ef('onKill', 'storeArchetype', { capability: 'summon' })] }),
  wpn({ id: 'cp_grave_tax_ledger', name: 'Grave-Tax Ledger', wtype: 'staff', rarity: 'rare', tier: 3, atk: 4, int: 3, classBound: 'necromancer', acquisition: 'class',
    desc: 'Necromancer · generates Death Debt when enemies die; spend it on a bounded bonus.',
    effects: [ef('onKill', 'addCounter', { key: 'deathDebt', scope: 'combat' }), ef('onHit', 'modDamage', { add: 1 })] }),
  wpn({ id: 'cp_drowned_kings_femur', name: "Drowned King's Femur", wtype: 'mace', rarity: 'epic', tier: 4, atk: 6, classBound: 'necromancer', acquisition: 'class',
    desc: 'Necromancer · summons gain armor but slowly lose health (applied as a summon flag).',
    effects: [ef('onKill', 'summonAlly', { archetype: 'skeleton', once: 'combat', capability: 'summon' })] }),
  wpn({ id: 'cp_echo_party_lantern', name: 'Echo-Party Lantern', wtype: 'staff', rarity: 'epic', tier: 4, atk: 5, classBound: 'necromancer', acquisition: 'class',
    desc: 'Necromancer · temporary echo of an ally basic (depth 1, generated).',
    effects: [ef('onTurnEnd', 'echoAction', { mult: 0.4, once: 'combat', capability: 'echo_copy' })] }),
  wpn({ id: 'cp_scythe_unlived_deaths', name: 'Scythe of Unlived Deaths', wtype: 'axe', rarity: 'rare', tier: 3, atk: 6, classBound: 'necromancer', acquisition: 'class',
    desc: 'Necromancer · marks possible deaths; consuming marks creates a stronger result.',
    effects: [ef('onHit', 'applyStatus', { status: 'marked', turns: 2 }), ef('onHit', 'modDamage', { when: { targetMarked: true }, mult: 1.15 })] }),
  wpn({ id: 'cp_corpse_flower_sickle', name: 'Corpse-Flower Sickle', wtype: 'dagger', rarity: 'legendary', tier: 5, atk: 8, int: 4, classBound: 'necromancer', acquisition: 'class', unique: true,
    desc: 'Legendary · grows different blooms from burned, poisoned, frozen, or cursed corpses.',
    effects: [ef('onKill', 'heal', { pct: 0.08, when: { status: 'burn' } }), ef('onKill', 'grantResource', { amount: 10 })] }),

  /* Spellsword */
  wpn({ id: 'cp_inward_gate_blade', name: 'Inward-Gate Blade', wtype: 'sword', rarity: 'rare', tier: 3, atk: 6, int: 2, classBound: 'spellsword', acquisition: 'class',
    desc: 'Spellsword · alternating spell and weapon opens a hybrid strike (depth 1).',
    effects: [ef('onHit', 'echoAction', { mult: 0.4, when: { differentFromPrior: true }, once: 'turn', capability: 'echo_copy' })] }),
  wpn({ id: 'cp_mirror_exchange_saber', name: 'Mirror-Exchange Saber', wtype: 'sword', rarity: 'epic', tier: 4, atk: 6, classBound: 'spellsword', acquisition: 'class',
    desc: 'Spellsword · copies one enemy buff but transfers one player buff in exchange.',
    effects: [ef('onHit', 'convertStatus', { status: 'weaken', statusTo: 'frail', once: 'combat' })] }),
  wpn({ id: 'cp_rapier_tomorrows_notes', name: "Rapier of Tomorrow's Notes", wtype: 'sword', rarity: 'rare', tier: 3, atk: 5, int: 2, classBound: 'spellsword', acquisition: 'class',
    desc: 'Spellsword · preparing a technique displays how the weapon will modify it next turn.',
    effects: [ef('onSkillUse', 'storeMemory', { key: 'preview', scope: 'turn' }), ef('onHit', 'modDamage', { add: 2 })] }),
  wpn({ id: 'cp_truth_furnace_brand', name: 'Truth-Furnace Brand', wtype: 'sword', rarity: 'epic', tier: 4, atk: 7, classBound: 'spellsword', acquisition: 'class',
    desc: 'Spellsword · strips one beneficial and one harmful status, converting both into damage.',
    effects: [ef('onHit', 'removeStatus', { status: 'weaken' }), ef('onHit', 'modDamage', { add: 4, once: 'turn' })] }),
  wpn({ id: 'cp_split_gate_twinblade', name: 'Split-Gate Twinblade', wtype: 'sword', rarity: 'epic', tier: 4, atk: 6, int: 2, classBound: 'spellsword', acquisition: 'class',
    desc: 'Spellsword · physical and magical halves empower each other when alternated.',
    effects: [ef('onHit', 'modDamage', { mult: 1.12, when: { differentFromPrior: true } })] }),
  wpn({ id: 'cp_seventh_owner_sword', name: 'Seventh-Owner Sword', wtype: 'sword', rarity: 'unique', tier: 5, atk: 14, classBound: 'spellsword', acquisition: 'unique', unique: true, quest: true,
    desc: 'UNIQUE evolving blade. Final rider depends on owner-chain flags (normalized). One owner at a time.',
    effects: [ef('onHit', 'modDamage', { mult: 1.15 }), ef('onKill', 'evolveItem', { itemId: 'cp_seventh_owner_sword' })] }),

  /* Warlock parity */
  wpn({ id: 'cp_clause_seven_stylus', name: 'Clause-Seven Stylus', wtype: 'dagger', rarity: 'rare', tier: 3, atk: 5, int: 2, classBound: 'warlock', acquisition: 'class',
    desc: 'Warlock · hexed targets pay a small Pact refund on hit.',
    effects: [ef('onHit', 'grantResource', { amount: 3, when: { status: 'hexed' } })] }),
  wpn({ id: 'cp_appeal_denied_grimoire', name: 'Appeal-Denied Grimoire', wtype: 'staff', rarity: 'epic', tier: 4, atk: 5, int: 4, classBound: 'warlock', acquisition: 'class',
    desc: 'Warlock · stronger against enemies enforcing marks, judgments, or contracts.',
    effects: [ef('onHit', 'modDamage', { vsStatus: 'hexed', mult: 1.16 })] }),
  wpn({ id: 'cp_invoice_quill', name: 'Invoice Quill', wtype: 'dagger', rarity: 'rare', tier: 3, atk: 4, int: 3, classBound: 'warlock', acquisition: 'class',
    desc: 'Warlock · spending Pact empowers the next hex.',
    effects: [ef('onSkillUse', 'setFlag', { key: 'invoiced', scope: 'turn' }), ef('onHit', 'modDamage', { mult: 1.12, when: { flag: 'invoiced' } })] }),
  wpn({ id: 'cp_unregistered_pact_blade', name: 'Unregistered Pact Blade', wtype: 'dagger', rarity: 'epic', tier: 4, atk: 6, classBound: 'warlock', acquisition: 'class',
    desc: 'Warlock · stronger at low Fame; weakens as official recognition rises.',
    effects: [ef('onHit', 'modDamage', { mult: 1.16, when: { fameBelow: 6 } })] }),
  wpn({ id: 'cp_hell_margin_scepter', name: 'Hell-Margin Scepter', wtype: 'staff', rarity: 'epic', tier: 4, atk: 6, int: 3, classBound: 'warlock', acquisition: 'class',
    desc: 'Warlock · once per combat, contest a punitive effect at a visible HP price.',
    effects: [ef('beforeDamageTaken', 'contestLethal', { amount: 8, once: 'combat' })] }),
  wpn({ id: 'cp_seventh_signature_contract', name: 'Seventh-Signature Contract', wtype: 'staff', rarity: 'legendary', tier: 5, atk: 10, int: 5, classBound: 'warlock', acquisition: 'class', unique: true,
    desc: 'Legendary · stores one safe minor archetype from a hexed kill.',
    effects: [ef('onKill', 'storeArchetype'), ef('onHit', 'applyStatus', { status: 'hexed', turns: 2 })] }),

  /* Viking parity */
  wpn({ id: 'cp_raid_prow_axe', name: 'Raid-Prow Axe', wtype: 'axe', rarity: 'rare', tier: 3, atk: 7, str: 2, classBound: 'viking', acquisition: 'class',
    desc: 'Viking · lifesteal window after a self-cost technique.',
    effects: [ef('onHit', 'heal', { pct: 0.03, once: 'turn' })] }),
  wpn({ id: 'cp_shield_biters_maul', name: "Shield-Biter's Maul", wtype: 'mace', rarity: 'epic', tier: 4, atk: 8, classBound: 'viking', acquisition: 'class',
    desc: 'Viking · extra damage to shields; fury on being hit.',
    effects: [ef('onHit', 'modDamage', { vsShielded: 1.18 }), ef('onDamageTaken', 'grantResource', { amount: 2, once: 'turn' })] }),
  wpn({ id: 'cp_oath_to_the_keel', name: 'Oath to the Keel', wtype: 'axe', rarity: 'rare', tier: 3, atk: 6, classBound: 'viking', acquisition: 'class',
    desc: 'Viking · choose an oath after a major wound.',
    effects: [ef('onDamageTaken', 'setOath', { oath: 'avenge', when: { hpBelow: 0.5 } })] }),
  wpn({ id: 'cp_longship_hook', name: 'Longship Hook', wtype: 'axe', rarity: 'epic', tier: 4, atk: 7, classBound: 'viking', acquisition: 'class',
    desc: 'Viking · pulls attention and stores raid momentum.',
    effects: [
      ef('onHit', 'setFlag', { key: 'raidHook', scope: 'combat' }),
      ef('onHit', 'modDamage', { add: 3, when: { flag: 'raidHook' } }),
    ] }),
  wpn({ id: 'cp_frost_wake_cleaver', name: 'Frost-Wake Cleaver', wtype: 'axe', rarity: 'epic', tier: 4, atk: 8, freeze: 0.1, classBound: 'viking', acquisition: 'class',
    desc: 'Viking · extra damage to frozen or stunned targets.',
    effects: [ef('onHit', 'modDamage', { vsStatus: 'frozen', mult: 1.18 })] }),
  wpn({ id: 'cp_valhalla_boarding_axe', name: 'Valhalla Boarding Axe', wtype: 'axe', rarity: 'legendary', tier: 5, atk: 12, str: 4, classBound: 'viking', acquisition: 'class', unique: true,
    desc: 'Legendary · once per combat, a killing blow refunds a sliver of Fury and HP.',
    effects: [ef('onKill', 'heal', { pct: 0.12, once: 'combat' }), ef('onKill', 'grantResource', { amount: 12, once: 'combat' })] }),
];
