import { wpn, ef } from './helpers.js';

export const PACK_WEAPONS_RESONANT = [
  wpn({ id: 'cp_many_banner_longsword', name: 'Many-Banner Longsword', wtype: 'sword', rarity: 'uncommon', tier: 2, atk: 6, resonance: 'human', acquisition: 'bloodline',
    desc: 'Human-resonant · copies a modest property from the most recently equipped weapon. Humans may change it at campfires.',
    effects: [ef('onCampfire', 'storeMemory', { key: 'copiedProp', scope: 'run', when: { bloodline: 'human' } }),
      ef('onHit', 'modDamage', { add: 1 })] }),
  wpn({ id: 'cp_witness_spear', name: 'Witness Spear', wtype: 'spear', rarity: 'uncommon', tier: 2, atk: 6, resonance: 'human', acquisition: 'bloodline',
    desc: 'Human-resonant · improves after observing a new enemy special; Humans retain one observation between combats.',
    effects: [ef('onIntentRevealed', 'storeMemory', { key: 'observedSpecial', scope: 'run' }),
      ef('onHit', 'modDamage', { add: 2, when: { bloodline: 'human' } })] }),
  wpn({ id: 'cp_borrowed_tradition_blade', name: 'Borrowed-Tradition Blade', wtype: 'sword', rarity: 'epic', tier: 4, atk: 7, resonance: 'human', acquisition: 'bloodline',
    desc: 'Human-resonant · resonates with the active class rather than a fixed style.',
    effects: [ef('onHit', 'modDamage', { mult: 1.08 })] }),
  wpn({ id: 'cp_memory_branch_bow', name: 'Memory-Branch Bow', wtype: 'bow', rarity: 'uncommon', tier: 2, atk: 6, resonance: 'elf', acquisition: 'bloodline',
    desc: 'Elf-resonant · remembers the first marked target family and improves later encounters.',
    effects: [ef('onHit', 'storeMemory', { key: 'memoryFamily', scope: 'run' }),
      ef('onHit', 'modDamage', { add: 2, when: { bloodline: 'elf' } })] }),
  wpn({ id: 'cp_moonroot_spear', name: 'Moonroot Spear', wtype: 'spear', rarity: 'epic', tier: 4, atk: 7, resonance: 'elf', acquisition: 'bloodline',
    desc: 'Elf-resonant · grows stronger during longer fights; Elves choose growth direction.',
    effects: [ef('onTurnStart', 'addCounter', { key: 'moonroot', scope: 'combat' }),
      ef('onHit', 'modDamage', { add: 1 })] }),
  wpn({ id: 'cp_silverleaf_duelling_blade', name: 'Silverleaf Duelling Blade', wtype: 'sword', rarity: 'rare', tier: 3, atk: 5, dex: 2, resonance: 'elf', acquisition: 'bloodline',
    desc: 'Elf-resonant · rewards patient defense before one precise attack.', effects: [
      ef('onGuard', 'setFlag', { key: 'patient', scope: 'turn' }),
      ef('onHit', 'modDamage', { mult: 1.18, when: { flag: 'patient' } }),
    ] }),
  wpn({ id: 'cp_tollbreaker_cleaver', name: 'Tollbreaker Cleaver', wtype: 'axe', rarity: 'uncommon', tier: 2, atk: 7, resonance: 'orc', acquisition: 'bloodline',
    desc: 'Orc-resonant · converts part of gold paid during events into stored fury (capped).',
    effects: [ef('onEventResolve', 'addCounter', { key: 'tollFury', scope: 'run', amount: 1 }),
      ef('onHit', 'modDamage', { add: 2, when: { bloodline: 'orc' } })] }),
  wpn({ id: 'cp_scar_oath_axe', name: 'Scar-Oath Axe', wtype: 'axe', rarity: 'epic', tier: 4, atk: 8, resonance: 'orc', acquisition: 'bloodline',
    desc: 'Orc-resonant · choose an oath after a major wound.',
    effects: [ef('onDamageTaken', 'setOath', { oath: 'avenge', when: { hpBelow: 0.45 } })] }),
  wpn({ id: 'cp_clan_weight_maul', name: 'Clan-Weight Maul', wtype: 'mace', rarity: 'uncommon', tier: 2, atk: 7, resonance: 'orc', acquisition: 'bloodline',
    desc: 'Orc-resonant · stronger when protecting lower-health allies; Orcs can take part of that damage.',
    effects: [ef('beforeDamageTaken', 'redirectDamage', { pct: 0.25, mutex: 'damage_redirect', when: { bloodline: 'orc' } })] }),
  wpn({ id: 'cp_gate_mason_hammer', name: 'Gate-Mason Hammer', wtype: 'mace', rarity: 'uncommon', tier: 2, atk: 6, resonance: 'dwarf', acquisition: 'bloodline',
    desc: 'Dwarf-resonant · better reforges at events; bonus vs constructed foes.',
    effects: [ef('onHit', 'modDamage', { vsFamily: 'golem', mult: 1.18 })] }),
  wpn({ id: 'cp_ledger_pick', name: 'Ledger Pick', wtype: 'axe', rarity: 'uncommon', tier: 2, atk: 6, resonance: 'dwarf', acquisition: 'bloodline',
    desc: 'Dwarf-resonant · reveals inflated prices and punishes constructed enemies.',
    effects: [ef('onHit', 'modDamage', { vsFamily: 'golem', mult: 1.15 })] }),
  wpn({ id: 'cp_remembering_kiln_tongs', name: 'Remembering Kiln Tongs', wtype: 'mace', rarity: 'epic', tier: 4, atk: 6, resonance: 'dwarf', acquisition: 'bloodline',
    desc: 'Dwarf-resonant · can reforge a selected item without destroying it, but may add a flaw (event).',
    effects: [ef('onHit', 'modDamage', { add: 1 })] }),
  wpn({ id: 'cp_pocket_gate_knife', name: 'Pocket-Gate Knife', wtype: 'dagger', rarity: 'uncommon', tier: 2, atk: 4, crit: 6, resonance: 'halfling', acquisition: 'bloodline',
    desc: 'Halfling-resonant · once per combat, a narrowly failed action becomes a partial success (bounded).',
    effects: [ef('onMiss', 'armNextHit', { add: 4, once: 'combat', when: { bloodline: 'halfling' } })] }),
  wpn({ id: 'cp_second_breakfast_sling', name: 'Second-Breakfast Sling', wtype: 'bow', rarity: 'uncommon', tier: 2, atk: 3, resonance: 'halfling', acquisition: 'bloodline',
    desc: 'Halfling-resonant · food consumables grant a small extra heal.',
    effects: [ef('onConsumable', 'heal', { amount: 6, when: { bloodline: 'halfling' } })] }),
  wpn({ id: 'cp_toll_skipping_cane', name: 'Toll-Skipping Cane', wtype: 'staff', rarity: 'uncommon', tier: 2, atk: 3, lk: 2, resonance: 'halfling', acquisition: 'bloodline',
    desc: 'Halfling-resonant · sometimes exposes a cheaper event payment; Halflings store one unused discount.',
    effects: [ef('onEventResolve', 'convertResource', { key: 'unminted', when: { bloodline: 'halfling' } })] }),
  wpn({ id: 'cp_appeal_denied_trident', name: 'Appeal-Denied Trident', wtype: 'spear', rarity: 'uncommon', tier: 2, atk: 6, resonance: 'tiefling', acquisition: 'bloodline',
    desc: 'Tiefling-resonant · stronger against enemies enforcing contracts, laws, marks, or judgments.',
    effects: [ef('onHit', 'modDamage', { vsStatus: 'hexed', mult: 1.16 })] }),
  wpn({ id: 'cp_fine_print_lash', name: 'Fine-Print Lash', wtype: 'dagger', rarity: 'epic', tier: 4, atk: 5, resonance: 'tiefling', acquisition: 'bloodline',
    desc: 'Tiefling-resonant · extends a beneficial effect and one negative effect.',
    effects: [ef('onHit', 'extendStatus', { status: 'marked', turns: 1, selfHarm: true })] }),
  wpn({ id: 'cp_ember_ink_dagger', name: 'Ember-Ink Dagger', wtype: 'dagger', rarity: 'uncommon', tier: 2, atk: 5, burn: 0.12, resonance: 'tiefling', acquisition: 'bloodline',
    desc: 'Tiefling-resonant · writes a burning clause; Tieflings choose the trigger.',
    effects: [ef('onHit', 'statusChance', { status: 'burn', chance: 0.25, when: { bloodline: 'tiefling' } })] }),
  wpn({ id: 'cp_scent_of_tomorrow_claws', name: 'Scent-of-Tomorrow Claws', wtype: 'fist', rarity: 'uncommon', tier: 2, atk: 6, resonance: 'beastfolk', acquisition: 'bloodline',
    desc: 'Beastfolk-resonant · first enemy targeted becomes Prey; scent persists through transformations (family id).',
    effects: [ef('onHit', 'markTarget'), ef('onCombatStart', 'storeMemory', { key: 'preyFamily', scope: 'run' })] }),
  wpn({ id: 'cp_pack_oath_spear', name: 'Pack-Oath Spear', wtype: 'spear', rarity: 'epic', tier: 4, atk: 7, resonance: 'beastfolk', acquisition: 'bloodline',
    desc: 'Beastfolk-resonant · different bonus if an ally last attacked the same target.',
    effects: [ef('onHit', 'modDamage', { mult: 1.1 })] }),
  wpn({ id: 'cp_moon_fang_shortbow', name: 'Moon-Fang Shortbow', wtype: 'bow', rarity: 'uncommon', tier: 2, atk: 6, resonance: 'beastfolk', acquisition: 'bloodline',
    desc: 'Beastfolk-resonant · improves pursuit and execution against weakened targets.',
    effects: [ef('onHit', 'modDamage', { vsStatus: 'weaken', mult: 1.16 })] }),
  wpn({ id: 'cp_hingefire_glaive', name: 'Hingefire Glaive', wtype: 'spear', rarity: 'epic', tier: 4, atk: 7, resonance: 'dragonkin', acquisition: 'bloodline',
    desc: 'Dragonkin-resonant · stores elemental residue; Dragonkin can release it.',
    effects: [ef('onHit', 'addCounter', { key: 'hingefire', scope: 'combat' }),
      ef('onHit', 'modDamage', { add: 3, when: { bloodline: 'dragonkin' }, once: 'turn' })] }),
  wpn({ id: 'cp_hoardscale_hammer', name: 'Hoardscale Hammer', wtype: 'mace', rarity: 'uncommon', tier: 2, atk: 6, resonance: 'dragonkin', acquisition: 'bloodline',
    desc: 'Dragonkin-resonant · slightly stronger with held gold; a shop action suppresses it for one combat.',
    effects: [ef('onHit', 'modDamage', { add: 1, when: { goldAtLeast: 40, notFlag: 'hoardSuppressed' } }),
      ef('onShopAction', 'setFlag', { key: 'hoardSuppressed', scope: 'floor' })] }),
  wpn({ id: 'cp_ancestral_verdict_spear', name: 'Ancestral Verdict Spear', wtype: 'spear', rarity: 'epic', tier: 4, atk: 7, resonance: 'dragonkin', acquisition: 'bloodline',
    desc: 'Dragonkin-resonant · stronger against bosses claiming royal, divine, or gatekeeping authority.',
    effects: [ef('onHit', 'modDamage', { vsBoss: 1.14 })] }),
];

export const PACK_WEAPONS_CURSED = [
  wpn({ id: 'cp_cowards_first_sword', name: "The Coward's First Sword", wtype: 'sword', rarity: 'rare', tier: 3, atk: 8, acquisition: 'cursed', curse: 'cannot_open_vs_full_hp',
    resolution: 'Owner-chain event Reject/Exorcise, or Nameless Saint refuse.',
    desc: 'Cursed · greatly strengthens retaliation, but cannot initiate against full-health enemies.',
    effects: [ef('onHit', 'modDamage', { mult: 1.22, when: { flag: 'retaliating' } }),
      ef('onDamageTaken', 'setFlag', { key: 'retaliating', scope: 'turn' })] }),
  wpn({ id: 'cp_coinmouth_maul', name: 'Coinmouth Maul', wtype: 'mace', rarity: 'epic', tier: 4, atk: 9, acquisition: 'cursed', curse: 'eats_gold',
    resolution: 'Fame Eater chain domestication, or Furnace of Honest Metal.',
    desc: 'Cursed · exceptional charged attacks consume gold; bites the wielder if funds run out.',
    effects: [ef('onHit', 'spendGoldPower', { gold: 6, mult: 1.25, selfHarm: true, amount: 5, when: { charged: true } })] }),
  wpn({ id: 'cp_applause_knife', name: 'Applause Knife', wtype: 'dagger', rarity: 'rare', tier: 3, atk: 5, crit: 10, acquisition: 'cursed', curse: 'eats_fame',
    resolution: 'Fame Eater chain or Bottle of Applause.',
    desc: 'Cursed · critical hits consume Fame; at zero Fame it consumes HP.',
    effects: [ef('onHit', 'spendFamePower', { fame: 1, mult: 1.2, selfHarm: true, when: { isCrit: true } })] }),
  wpn({ id: 'cp_crimson_checkpoint_blade', name: 'Crimson Checkpoint Blade', wtype: 'sword', rarity: 'epic', tier: 4, atk: 7, acquisition: 'cursed', curse: 'maxhp_ward', mutex: 'lethal_ward',
    resolution: 'Crimson Save Point chain: surrender the ward or admit the fraud.',
    desc: 'Cursed · prevents one lethal hit, then cracks and reduces max HP. Not a save-file restore.',
    effects: [ef('beforeDamageTaken', 'lethalWard', { mutex: 'lethal_ward', maxHp: -4, once: 'run' })] }),
  wpn({ id: 'cp_unregistered_hero_weapon', name: "The Unregistered Hero's Weapon", wtype: 'sword', rarity: 'rare', tier: 3, atk: 6, acquisition: 'cursed', curse: 'fame_inverse',
    resolution: 'Returned Extra chain: restore their name.',
    desc: 'Cursed · stronger at low Fame; weakens as official recognition rises.',
    effects: [ef('onHit', 'modDamage', { mult: 1.18, when: { fameBelow: 5 } })] }),
  wpn({ id: 'cp_gate_parasite_bow', name: 'Gate-Parasite Bow', wtype: 'bow', rarity: 'epic', tier: 4, atk: 7, acquisition: 'cursed', curse: 'parasite_return',
    resolution: 'Gate Parasites: Priest/Mage cleanse, or burn them away.',
    desc: 'Cursed · shots attach parasites; they may return when the target dies.',
    effects: [ef('onHit', 'statusChance', { status: 'poison', chance: 0.3 }),
      ef('onKill', 'applyStatus', { status: 'poison', turns: 1 })] }),
  wpn({ id: 'cp_previous_timeline_axe', name: "Previous Timeline's Axe", wtype: 'axe', rarity: 'epic', tier: 4, atk: 8, acquisition: 'cursed', curse: 'echo_last_skill',
    resolution: 'Echo Party: reject the copy, or prove System manipulation.',
    desc: 'Cursed · repeats the last technique from the previous fight at reduced power (depth 1). If unavailable, it nicks the user.',
    effects: [ef('onCombatStart', 'echoAction', { mult: 0.5, once: 'combat', capability: 'echo_copy' })] }),
  wpn({ id: 'cp_missing_eighth_oath', name: 'Sword of the Missing Eighth Oath', wtype: 'sword', rarity: 'epic', tier: 4, atk: 9, acquisition: 'cursed', curse: 'hidden_oath',
    resolution: 'Seven-Owner Blade: reject the future or Priest exorcise.',
    desc: 'Cursed · powerful, but one undisclosed combat behavior weakens it (normalized: repeating the same action).',
    effects: [ef('onHit', 'modDamage', { mult: 1.2, when: { differentFromPrior: true } })] }),
  wpn({ id: 'cp_funeral_receipt_dagger', name: 'Funeral Receipt Dagger', wtype: 'dagger', rarity: 'rare', tier: 3, atk: 5, acquisition: 'cursed', curse: 'gold_for_healing_cut',
    resolution: 'Grave-Tax Collector: Priest burial law, or Funeral Receipt consumable.',
    desc: 'Cursed · produces gold when enemies die but reduces post-combat healing.',
    effects: [ef('onKill', 'gainGold', { amount: 4 }), ef('onCombatEnd', 'setFlag', { key: 'healCut', scope: 'floor' })] }),
  wpn({ id: 'cp_false_system_staff', name: 'False System Staff', wtype: 'staff', rarity: 'epic', tier: 4, atk: 6, int: 3, acquisition: 'cursed', curse: 'corrupt_preview',
    resolution: 'False System chain: file an appeal with evidence.',
    desc: 'Cursed · occasionally upgrades a spell; the preview always warns when corruption is possible (never silent retarget).',
    effects: [ef('onHit', 'modDamage', { mult: 1.12 }), ef('onSkillUse', 'revealIntent', { value: 'corrupt_preview' })] }),
  wpn({ id: 'cp_crownless_kings_scepter', name: "Crownless King's Scepter", wtype: 'staff', rarity: 'epic', tier: 4, atk: 6, acquisition: 'cursed', curse: 'royal_aggro',
    resolution: 'Drowned Royal Family: refuse monarchy or return the crown.',
    desc: 'Cursed · command over summons, but royal/elite foes prioritize the wielder.',
    effects: [ef('onKill', 'summonAlly', { archetype: 'skeleton', once: 'combat', capability: 'summon' })] }),
  wpn({ id: 'cp_fame_eater_tooth', name: "Fame-Eater's Tooth", wtype: 'dagger', rarity: 'rare', tier: 3, atk: 5, acquisition: 'cursed', curse: 'fame_feed',
    resolution: 'Fame Eater chain: domesticate, kill, or become its agent.',
    desc: 'Cursed · consumes Fame to empower attacks.',
    effects: [ef('onHit', 'spendFamePower', { fame: 1, mult: 1.18, selfHarm: true, once: 'turn' })] }),
  wpn({ id: 'cp_bell_clapper_greatclub', name: 'Bell-Clapper Greatclub', wtype: 'mace', rarity: 'epic', tier: 4, atk: 9, acquisition: 'cursed', curse: 'needs_downed_ally',
    resolution: 'Bell of the Last Companion: ransom, rescue, or unanimous abandon.',
    desc: 'Cursed · devastating after an ally is downed or eliminated — never after a disconnect.',
    playable: 'adapted', adaptation: 'Triggers on authoritative downed/eliminated state only, never transient connection.',
    effects: [ef('onHit', 'modDamage', { mult: 1.28, when: { allyDowned: true } }),
      ef('onHit', 'modDamage', { mult: 0.9 })] }),
  wpn({ id: 'cp_drowned_brides_rapier', name: "Drowned Bride's Rapier", wtype: 'sword', rarity: 'epic', tier: 4, atk: 6, acquisition: 'cursed', curse: 'self_second_hit',
    resolution: 'Wedding Beneath the Ice: complete the ceremony or obtain Frozen Wedding Ring.',
    desc: 'Cursed · strikes twice against marked targets; the echo also nicks the wielder unless the matching ring is held.',
    effects: [ef('onHit', 'echoAction', { mult: 0.5, when: { targetMarked: true }, once: 'turn', capability: 'echo_copy' })] }),
  wpn({ id: 'cp_blade_lists_you', name: 'The Blade That Lists You as Equipment', wtype: 'sword', rarity: 'unique', tier: 5, atk: 12, acquisition: 'cursed', curse: 'unequip_wielder', quest: true, unique: true,
    resolution: 'Inventory Item: A Teammate — close the window or refuse the sale.',
    desc: 'UNIQUE · cursed. Strong while another party member is alive; at low HP it tries to "unequip" the wielder (lethal ward contest, not deletion). One listing per climber.',
    playable: 'adapted', adaptation: 'Cannot treat a player as an item. Low HP triggers a contest-lethal instead of unequipping a person.',
    effects: [ef('onHit', 'modDamage', { mult: 1.12 }),
      ef('beforeDamageTaken', 'contestLethal', { amount: 14, when: { hpBelow: 0.2 }, once: 'combat' })] }),
];
