"""Build js/data/sprite_present.js from an enemy-box editor export.

Combat mirrors enemy-boxes.html:
  1. Render the sprite at native combat scale (art.js / anim.js defaults)
  2. Wrap it in .sprite-wrap
  3. Apply translate(ox,oy) scale(±zoom, zoom) from this map
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXPORT = ROOT / "tools" / "enemy-box-settings-2026-07-21.json"
ANIMMAP = ROOT / "js" / "data" / "animmap.js"
ARTMAP = ROOT / "js" / "data" / "artmap.js"
OUT = ROOT / "js" / "data" / "sprite_present.js"


def score(item: dict) -> tuple:
    zoom = float(item.get("zoom") or 1)
    ox = int(item.get("offsetX") or 0)
    oy = int(item.get("offsetY") or 0)
    flip = 1 if item.get("flip") else 0
    dw = int((item.get("defaultBox") or {}).get("w") or item.get("defaultBoxW") or 96)
    dh = int((item.get("defaultBox") or {}).get("h") or item.get("defaultBoxH") or 96)
    bw = int(item.get("boxW") or dw)
    bh = int(item.get("boxH") or dh)
    box = 1 if (bw != dw or bh != dh) else 0
    section = item.get("section") or ""
    section_rank = 0 if section == "added" else 1
    return (zoom != 1.0, abs(ox) + abs(oy), flip, box, section_rank)


def pick_items(data: dict) -> dict[str, dict]:
    chosen: dict[str, dict] = {}
    for item in data.get("items") or []:
        if item.get("placeholder"):
            continue
        eid = item.get("id")
        if not eid:
            continue
        prev = chosen.get(eid)
        if prev is None or score(item) >= score(prev):
            chosen[eid] = item
    return chosen


def center_ids_from_maps() -> set[str]:
    """Ids that artmap/animmap mark as center-anchored (padded sheets)."""
    ids: set[str] = set()
    for path in (ANIMMAP, ARTMAP):
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8")
        # Match "id": { ... "anchor": "center" ... } within a reasonable window
        for m in re.finditer(
            r'"([a-z0-9_]+)"\s*:\s*\{([^{}]*(?:\{[^{}]*\}[^{]*)*)\}',
            text,
            re.I,
        ):
            body = m.group(2)
            if re.search(r'"anchor"\s*:\s*"center"', body):
                ids.add(m.group(1))
    return ids


def present_entry(item: dict, center_ids: set[str]) -> dict:
    default_scale = float(item.get("defaultScale") or 1)
    zoom = float(item.get("zoom") or 1)
    eff = item.get("effectiveScale")
    if eff is None:
        eff = default_scale * zoom
    else:
        eff = float(eff)
    dw = int((item.get("defaultBox") or {}).get("w") or item.get("defaultBoxW") or 96)
    dh = int((item.get("defaultBox") or {}).get("h") or item.get("defaultBoxH") or 96)
    bw = int(item.get("boxW") or dw)
    bh = int(item.get("boxH") or dh)
    eid = item["id"]
    # Match enemy-boxes.html buildCatalog anchor rules.
    if item.get("anchor") in ("center", "feet"):
        anchor = item["anchor"]
    elif eid in center_ids:
        anchor = "center"
    elif item.get("boss"):
        anchor = "feet"
    else:
        anchor = "center"
    return {
        "zoom": round(zoom, 3),
        "ox": int(item.get("offsetX") or 0),
        "oy": int(item.get("offsetY") or 0),
        "flip": bool(item.get("flip")),
        "boxW": bw,
        "boxH": bh,
        "anchor": anchor,
        "defaultScale": round(default_scale, 3),
        "scale": round(eff, 3),
    }


def main() -> None:
    data = json.loads(EXPORT.read_text(encoding="utf-8"))
    center_ids = center_ids_from_maps()
    picked = pick_items(data)
    present = {eid: present_entry(item, center_ids) for eid, item in sorted(picked.items())}
    tuned = sum(
        1
        for e in present.values()
        if e["zoom"] != 1 or e["ox"] or e["oy"] or e["flip"] or e["boxW"] not in (96, 200)
    )

    helper = '''
export function enemyPresent(id) {
  return ENEMY_PRESENT[id] || null;
}

/** Mirror enemy-boxes.html box + sprite-wrap presentation around inner sprite HTML. */
export function enemyBoxHtml(id, innerHtml, { boss = false, domId = "" } = {}) {
  const p = ENEMY_PRESENT[id] || null;
  const boxW = p?.boxW || (boss ? 200 : 96);
  const boxH = p?.boxH || (boss ? 200 : 96);
  const zoom = p?.zoom ?? 1;
  const ox = p?.ox ?? 0;
  const oy = p?.oy ?? 0;
  const flip = !!p?.flip;
  const anchor = p?.anchor || (boss ? "feet" : "center");
  const xf = `translate(${ox}px, ${oy}px) scale(${flip ? -zoom : zoom}, ${zoom})`;
  const idAttr = domId ? ` id="${domId}"` : "";
  return `<div class="fighter-sprite"${idAttr} data-anchor="${anchor}" style="width:${boxW}px;height:${boxH}px">`
    + `<div class="sprite-wrap" style="transform:${xf}">${innerHtml}</div>`
    + `</div>`;
}
'''.strip()

    lines = [
        "// GENERATED by tools/apply_enemy_box_present.py — do not edit by hand.",
        "// Source: tools/enemy-box-settings-2026-07-21.json",
        "// Combat applies zoom/nudge/flip on .sprite-wrap (same as enemy-boxes.html).",
        "export const ENEMY_PRESENT = " + json.dumps(present, indent=2) + ";",
        "",
        helper,
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} entries={len(present)} tuned={tuned} centerIds={len(center_ids)}")


if __name__ == "__main__":
    main()
